import { applySupportLoadInputOverridesToInput, normaliseSupportLoadInputOverrideState } from './GeometrySupportLoadInputOverrides.js?v=20260622-input-override-1';
export const SUPPORT_LOAD_INPUT_REVIEW_SCHEMA='support-load-input-review/v1';
export const SUPPORT_LOAD_INPUT_REVIEW_VERSION='20260622-input-review-override-lock-1';
function text(v){return String(v??'').trim();}
function fr(v){if(!v||typeof v!=='object')return v;if(Array.isArray(v))return Object.freeze(v.map(fr));return Object.freeze(Object.fromEntries(Object.entries(v).map(([k,x])=>[k,fr(x)])));}
export function supportLoadInputReviewKey(input){const i=input?.identity||{};return text(input?.sourceObjectId)||text(i.lineNo)||text(i.branchKey)||text(i.branchName)||'pipe-input';}
export function normaliseSupportLoadInputReviewState(state={}){const src=Array.isArray(state?.records)?state.records:Array.isArray(state)?state:Object.values(state?.records||{}),records={};for(const item of src){const key=text(item?.key);if(!key)continue;records[key]=fr({schema:SUPPORT_LOAD_INPUT_REVIEW_SCHEMA,key,locked:Boolean(item.locked),status:text(item.status)||(item.locked?'LOCKED':'OPEN'),reviewedAt:text(item.reviewedAt),reviewedBy:text(item.reviewedBy)||'geometry-workspace',reason:text(item.reason),missingAtReview:Array.isArray(item.missingAtReview)?item.missingAtReview.slice():[]});}const overrides=normaliseSupportLoadInputOverrideState(state?.overrides||state?.inputOverrides||{});return fr({schema:SUPPORT_LOAD_INPUT_REVIEW_SCHEMA,version:SUPPORT_LOAD_INPUT_REVIEW_VERSION,records,overrides});}
function record(input,state){const key=supportLoadInputReviewKey(input),prior=state.records?.[key],miss=Array.isArray(input?.readiness?.missing)?input.readiness.missing:[],ready=input?.readiness?.status==='INPUT_READY',overrideCount=Object.keys(input?.inputOverrides?.overrides||{}).length;return fr({schema:SUPPORT_LOAD_INPUT_REVIEW_SCHEMA,version:SUPPORT_LOAD_INPUT_REVIEW_VERSION,key,locked:Boolean(prior?.locked),status:prior?.locked?'LOCKED':ready?'READY_TO_LOCK':'REVIEW_REQUIRED',reviewedAt:text(prior?.reviewedAt),reviewedBy:text(prior?.reviewedBy)||'geometry-workspace',reason:text(prior?.reason||(ready?'Ready but not locked.':'Missing input fields.')),missingAtReview:prior?.missingAtReview?.length?prior.missingAtReview.slice():miss.slice(),overrideCount});}
function withReview(input,state){const inputReview=record(input,state),r=input?.readiness||{};return fr({...input,inputReview,readiness:{...r,lockedForCalculation:inputReview.locked,readyForCalculation:inputReview.locked&&r.status==='INPUT_READY',calculationGateStatus:inputReview.locked&&r.status==='INPUT_READY'?'INPUT_LOCKED':'INPUT_REVIEW_REQUIRED'}});}
function replaceObj(o,map){const input=o?.attributes?.supportLoadInput;if(!input)return o;const reviewed=map.get(supportLoadInputReviewKey(input));return reviewed?fr({...o,attributes:{...(o.attributes||{}),supportLoadInput:reviewed},supportLoadInput:reviewed}):o;}
function replaceRow(row,map){const input=row?.input?.pipeSupportLoadInput;if(!input)return row;const reviewed=map.get(supportLoadInputReviewKey(input));return reviewed?fr({...row,status:reviewed.readiness?.status||row.status,input:{...(row.input||{}),pipeSupportLoadInput:reviewed,inputReview:reviewed.inputReview,inputOverrides:reviewed.inputOverrides},inputReview:reviewed.inputReview,inputOverrides:reviewed.inputOverrides,calculationGateStatus:reviewed.readiness?.calculationGateStatus,missingFields:reviewed.readiness?.missing||row.missingFields||[]}):row;}
export function applySupportLoadInputReview(model,stateInput={}){if(!model||typeof model!=='object')return model;const state=normaliseSupportLoadInputReviewState(stateInput);const pipeInputs=(Array.isArray(model.pipeInputs)?model.pipeInputs:[]).map(input=>applySupportLoadInputOverridesToInput(input,state.overrides)).map(input=>withReview(input,state));const map=new Map(pipeInputs.map(input=>[supportLoadInputReviewKey(input),input]));const hydratedObjects=(Array.isArray(model.hydratedObjects)?model.hydratedObjects:[]).map(o=>replaceObj(o,map));const rows=(Array.isArray(model.rows)?model.rows:[]).map(row=>replaceRow(row,map));const locked=pipeInputs.filter(input=>input.inputReview?.locked).length,ready=pipeInputs.filter(input=>input.readiness?.status==='INPUT_READY').length,calcReady=pipeInputs.filter(input=>input.readiness?.readyForCalculation).length,overridden=pipeInputs.filter(input=>Object.keys(input.inputOverrides?.overrides||{}).length).length;return fr({...model,reviewSchema:SUPPORT_LOAD_INPUT_REVIEW_SCHEMA,reviewVersion:SUPPORT_LOAD_INPUT_REVIEW_VERSION,pipeInputs,rows,hydratedObjects,inputReview:state,inputLockedCount:locked,inputOpenCount:Math.max(0,pipeInputs.length-locked),inputOverrideCount:overridden,calcReadyPipeInputCount:calcReady,status:model.status==='EMPTY'?'EMPTY':calcReady&&calcReady===ready&&ready>0?'INPUT_LOCKED':'INPUT_REVIEW_REQUIRED',noLoadFormula:true});}
export function lockReadySupportLoadInputs(model,previousState={},options={}){const state=normaliseSupportLoadInputReviewState(previousState),records={...(state.records||{})};for(const input of model?.pipeInputs||[]){if(input?.readiness?.status!=='INPUT_READY')continue;const key=supportLoadInputReviewKey(input);records[key]=fr({schema:SUPPORT_LOAD_INPUT_REVIEW_SCHEMA,key,locked:true,status:'LOCKED',reviewedAt:options.reviewedAt||new Date().toISOString(),reviewedBy:text(options.reviewedBy)||'geometry-workspace',reason:text(options.reason)||'Input package locked for support-load calculation.',missingAtReview:[]});}return fr({schema:SUPPORT_LOAD_INPUT_REVIEW_SCHEMA,version:SUPPORT_LOAD_INPUT_REVIEW_VERSION,records,overrides:state.overrides});}
export function unlockSupportLoadInputs(model,previousState={},options={}){const state=normaliseSupportLoadInputReviewState(previousState),records={...(state.records||{})};for(const input of model?.pipeInputs||[]){const key=supportLoadInputReviewKey(input);records[key]=fr({schema:SUPPORT_LOAD_INPUT_REVIEW_SCHEMA,key,locked:false,status:'OPEN',reviewedAt:options.reviewedAt||new Date().toISOString(),reviewedBy:text(options.reviewedBy)||'geometry-workspace',reason:text(options.reason)||'Input lock cleared for review.',missingAtReview:Array.isArray(input?.readiness?.missing)?input.readiness.missing.slice():[]});}return fr({schema:SUPPORT_LOAD_INPUT_REVIEW_SCHEMA,version:SUPPORT_LOAD_INPUT_REVIEW_VERSION,records,overrides:state.overrides});}
