export const SUPPORT_LOAD_CONFLICT_SCHEMA = 'support-load-enrichment-conflict/v1';
export const SUPPORT_LOAD_CONFLICT_VERSION = '20260623-support-load-conflict-resolver-1';
export const SUPPORT_LOAD_CONFLICT_MODULE_ID = 'support-load-enrichment-conflict-resolver/v1';

const FIELD_DEFS = Object.freeze([
  { path: 'identity.nps', label: 'NPS', type: 'number', tolerance: 0.0001, input: ['identity', 'nps'], raw: ['NS', 'NPS', 'NOMINAL_SIZE', 'PIPE_SIZE'], object: [['pipe', 'nps'], ['nps']] },
  { path: 'identity.pipeOdMm', label: 'Pipe OD mm', type: 'number', tolerance: 1.5, input: ['identity', 'pipeOdMm'], raw: ['PipeOD', 'PIPE_OD', 'OD_MM', 'OD', 'DIA', 'DIAMETER', 'BORE'], object: [['pipe', 'odMm']] },
  { path: 'pipePhysical.wallThicknessMm', label: 'Wall thickness mm', type: 'number', tolerance: 0.25, input: ['pipePhysical', 'wallThicknessMm'], raw: ['WALL_THICK', 'WALL_THICKNESS_MM', 'WT_MM', 'THK_MM'], object: [['pipe', 'wallThicknessMm']], enrichment: [['geometryEnrichment', 'piping', 'wallThicknessMm']] },
  { path: 'pipePhysical.insideDiameterMm', label: 'Inside diameter mm', type: 'number', tolerance: 1.5, input: ['pipePhysical', 'insideDiameterMm'], object: [['pipe', 'insideDiameterMm']] },
  { path: 'pipePhysical.materialDensityKgM3', label: 'Material density kg/m3', type: 'number', tolerance: 1, input: ['pipePhysical', 'materialDensityKgM3'], raw: ['MATERIAL_DENSITY_KG_M3'], object: [['pipe', 'materialDensityKgM3']] },
  { path: 'pipePhysical.unitPipeWtKgPerM', label: 'Pipe weight kg/m', type: 'number', tolerance: 0.01, input: ['pipePhysical', 'unitPipeWtKgPerM'], raw: ['UnitPipewtKg/m', 'UNIT_PIPE_WT_KG_M', 'PIPE_WT_KG_M', 'WEIGHT_KG_M'], object: [['pipe', 'unitPipeWtKgPerM'], ['pipe', 'weightKgM']] },
  { path: 'process.tempExpC1', label: 'TEMP_EXP_C1', type: 'number', tolerance: 0.01, input: ['process', 'tempExpC1'], raw: ['TEMP_EXP_C1', 'TEMP_C1', 'DESIGN_TEMP_C'], object: [['process', 'temperature1C'], ['process', 'temperatureC']], enrichment: [['geometryEnrichment', 'process', 'temperature1C']] },
  { path: 'process.tempExpC2', label: 'TEMP_EXP_C2', type: 'number', tolerance: 0.01, input: ['process', 'tempExpC2'], raw: ['TEMP_EXP_C2', 'TEMP_C2'], object: [['process', 'temperature2C']], enrichment: [['geometryEnrichment', 'process', 'temperature2C']] },
  { path: 'process.fluidDensityOpeKgM3', label: 'OPE density kg/m3', type: 'number', tolerance: 0.01, input: ['process', 'fluidDensityOpeKgM3'], raw: ['FLUID_DENSITY_OPE_KG_M3', 'DENSITY_MIXED', 'DENSITY'], object: [['process', 'fluidDensityOpeKgM3'], ['process', 'fluidDensityKgM3']], enrichment: [['geometryEnrichment', 'process', 'fluidDensityKgM3']] },
  { path: 'process.fluidDensityHydKgM3', label: 'HYD density kg/m3', type: 'number', tolerance: 0.01, input: ['process', 'fluidDensityHydKgM3'], raw: ['FLUID_DENSITY_HYD_KG_M3', 'HYD_DENSITY_KG_M3', 'HYDRO_DENSITY'], object: [['process', 'fluidDensityHydKgM3'], ['process', 'hydroFluidDensityKgM3']] },
  { path: 'process.fluidWtOpeKgPerM', label: 'OPE fluid weight kg/m', type: 'number', tolerance: 0.01, input: ['process', 'fluidWtOpeKgPerM'], raw: ['FluidwtKg/m', 'FLUID_WT_OPE_KG_M', 'FLUIDWT_KG_M'], object: [['process', 'fluidWtOpeKgPerM']] },
  { path: 'process.fluidWtHydKgPerM', label: 'HYD fluid weight kg/m', type: 'number', tolerance: 0.01, input: ['process', 'fluidWtHydKgPerM'], raw: ['FLUID_WT_HYD_KG_M', 'HYD_FLUIDWT_KG_M'], object: [['process', 'fluidWtHydKgPerM']] },
  { path: 'spans.autoSpanMm', label: 'AutoSpan mm', type: 'number', tolerance: 1, input: ['spans', 'autoSpanMm'], raw: ['AutoSpan', 'AUTOSPAN_MM', 'AUTO_SPAN_MM'], object: [['spans', 'autoSpanMm']] },
  { path: 'spans.depSpanMm', label: 'DEPSpan mm', type: 'number', tolerance: 1, input: ['spans', 'depSpanMm'], raw: ['DEP SPAN', 'DEP_SPAN', 'DEPSPAN', 'DEPSPAN_MM'], object: [['spans', 'depSpanMm']] },
  { path: 'formulaProfile.roundStep', label: 'Rounding step', type: 'number', tolerance: 0.0001, input: ['formulaProfile', 'roundStep'], raw: ['ROUND_STEP'] },
  { path: 'formulaProfile.tempFunctionProfileId', label: 'TempfnC profile', type: 'text', input: ['formulaProfile', 'tempFunctionProfileId'], raw: ['TEMP_FUNCTION_PROFILE'] }
]);

function text(value) { return String(value ?? '').trim(); }
function norm(value) { return text(value).toUpperCase().replace(/[^A-Z0-9.]+/g, ''); }
function num(value) { if (typeof value === 'number') return Number.isFinite(value) ? value : null; const match = text(value).replace(/,/g, '').match(/[-+]?\d*\.?\d+(?:e[-+]?\d+)?/i); if (!match) return null; const n = Number(match[0]); return Number.isFinite(n) ? n : null; }
function isObject(value) { return value && typeof value === 'object'; }
function at(object, path = []) { return path.reduce((node, key) => isObject(node) ? node[key] : undefined, object); }
function rawFields(object) { return { ...(object?.rawRecord?.rawFields || {}), ...(object?.rawFields || {}) }; }
function rawValue(raw, keys = []) { const entries = Object.entries(raw || {}); for (const key of keys) { if (text(raw[key])) return raw[key]; const match = entries.find(([name, value]) => norm(name) === norm(key) && text(value)); if (match) return match[1]; } return undefined; }
function objectId(object) { return text(object?.sourceId || object?.id || object?.canonicalId || object?.displayName); }
function lineLabel(object, input) { return text(input?.identity?.lineNo || input?.identity?.branchName || object?.lineNo || object?.displayName || objectId(object)); }
function normalizeValue(value, type) { if (type === 'number') return num(value); const v = text(value); return v || null; }
function addCandidate(list, source, field, value, meta = {}) { const normalizedValue = normalizeValue(value, meta.type); if (normalizedValue === null || normalizedValue === undefined || normalizedValue === '') return; list.push(Object.freeze({ source, field, value, normalizedValue, ...meta })); }
function distinctValues(candidates, def) { const values = []; for (const candidate of candidates) { const value = normalizeValue(candidate.value, def.type); if (value === null || value === undefined || value === '') continue; if (def.type === 'number') { if (!values.some(item => Math.abs(Number(item) - Number(value)) <= (def.tolerance ?? 0))) values.push(Number(value)); } else if (!values.some(item => norm(item) === norm(value))) values.push(String(value)); } return values; }
function criticalField(path) { return /nps|pipeOdMm|wallThicknessMm|tempExpC1|unitPipeWtKgPerM|fluidWt|autoSpanMm|depSpanMm/i.test(path); }
function conflictsFor(def, candidates) { const values = distinctValues(candidates, def); if (values.length <= 1) return null; return Object.freeze({ schema: 'support-load-field-conflict/v1', fieldPath: def.path, label: def.label, type: def.type, tolerance: def.tolerance ?? null, values: Object.freeze(values), sources: Object.freeze(candidates.map(candidate => Object.freeze({ source: candidate.source, field: candidate.field, value: candidate.value }))), status: 'REVIEW_REQUIRED', severity: criticalField(def.path) ? 'HIGH' : 'MEDIUM' }); }
function auditCandidates(input, def, list) { for (const row of Array.isArray(input?.audit) ? input.audit : []) { if (!row || row.field !== def.path && row.field !== `pipe.attributes.supportLoadInput.${def.path}`) continue; addCandidate(list, row.source || 'AUDIT', row.field, row.value, { type: def.type, audit: true }); } }
function overrideCandidates(input, def, list) { const overrides = input?.inputOverrides?.overrides || {}; const override = overrides[def.path] || overrides[`pipe.attributes.supportLoadInput.${def.path}`]; if (override) addCandidate(list, 'REVIEWED_OVERRIDE', def.path, override.value, { type: def.type, reason: override.reason || override.source || '' }); }
function collectCandidates(object, input, def) { const raw = rawFields(object); const list = []; addCandidate(list, 'HYDRATED_PIPE_INPUT', def.path, at(input, def.input), { type: def.type }); addCandidate(list, 'NATIVE_RAW_ATTRIBUTE', (def.raw || []).join('|'), rawValue(raw, def.raw || []), { type: def.type }); for (const path of def.object || []) addCandidate(list, 'MAPPED_OBJECT_ATTRIBUTE', path.join('.'), at(object, path), { type: def.type }); for (const path of def.enrichment || []) addCandidate(list, 'XML_CII_ENRICHMENT', path.join('.'), at(object, path), { type: def.type }); auditCandidates(input, def, list); overrideCandidates(input, def, list); return Object.freeze(list); }
function rowForPipe(object) { const input = object?.attributes?.supportLoadInput || object?.supportLoadInput || null; if (!input) return null; const fieldConflicts = []; const fields = []; for (const def of FIELD_DEFS) { const candidates = collectCandidates(object, input, def); const conflict = conflictsFor(def, candidates); fields.push(Object.freeze({ fieldPath: def.path, label: def.label, candidateCount: candidates.length, candidates, status: conflict ? 'CONFLICT' : candidates.length ? 'CONSISTENT' : 'MISSING' })); if (conflict) fieldConflicts.push(conflict); } return Object.freeze({ schema: 'support-load-pipe-conflict-row/v1', objectId: objectId(object), lineNo: lineLabel(object, input), status: fieldConflicts.length ? 'REVIEW_REQUIRED' : 'NO_CONFLICT', conflictCount: fieldConflicts.length, highSeverityCount: fieldConflicts.filter(item => item.severity === 'HIGH').length, fieldConflicts: Object.freeze(fieldConflicts), fields: Object.freeze(fields) }); }
function isPipeInputObject(object) { return !!(object?.attributes?.supportLoadInput || object?.supportLoadInput); }
export function buildSupportLoadEnrichmentConflictModel(objects = [], options = {}) { const rows = Object.freeze((Array.isArray(objects) ? objects : []).filter(isPipeInputObject).map(rowForPipe).filter(Boolean)); const conflictCount = rows.reduce((sum, row) => sum + row.conflictCount, 0); const highSeverityCount = rows.reduce((sum, row) => sum + row.highSeverityCount, 0); return Object.freeze({ schema: SUPPORT_LOAD_CONFLICT_SCHEMA, version: SUPPORT_LOAD_CONFLICT_VERSION, moduleId: SUPPORT_LOAD_CONFLICT_MODULE_ID, evaluatedAt: options.evaluatedAt || new Date().toISOString(), pipeCount: rows.length, conflictCount, highSeverityCount, status: conflictCount ? 'REVIEW_REQUIRED' : rows.length ? 'NO_CONFLICT' : 'NO_PIPE_INPUTS', rows, policy: Object.freeze({ noSilentTopUp: true, noFormulaExecution: true, noCalculatedFieldMutation: true, action: 'Review conflicts before locking/recalculating support loads.' }) }); }
export function summarizeSupportLoadEnrichmentConflicts(model) { const m = model && model.schema === SUPPORT_LOAD_CONFLICT_SCHEMA ? model : buildSupportLoadEnrichmentConflictModel([]); return Object.freeze({ schema: 'support-load-enrichment-conflict-summary/v1', pipeCount: m.pipeCount || 0, conflictCount: m.conflictCount || 0, highSeverityCount: m.highSeverityCount || 0, status: m.status || 'NO_PIPE_INPUTS' }); }
