import { buildGeometrySupportLoadInputModel, exampleSupportLoadInputObjects, GEOMETRY_SUPPORT_LOAD_INPUT_SCHEMA, GEOMETRY_SUPPORT_LOAD_INPUT_VERSION, PIPE_SUPPORT_LOAD_INPUT_SCHEMA } from './GeometrySupportLoadInputModel.js?v=20260623-autospan-resolver-1';
import { applySupportLoadInputReview, lockReadySupportLoadInputs, unlockSupportLoadInputs, supportLoadInputReviewKey, SUPPORT_LOAD_INPUT_REVIEW_SCHEMA, SUPPORT_LOAD_INPUT_REVIEW_VERSION } from './GeometrySupportLoadInputReview.js?v=20260622-input-review-override-lock-1';
import { SUPPORT_LOAD_INPUT_OVERRIDE_FIELDS, SUPPORT_LOAD_INPUT_OVERRIDE_SCHEMA, SUPPORT_LOAD_INPUT_OVERRIDE_VERSION, setSupportLoadInputOverride, clearSupportLoadInputOverride } from './GeometrySupportLoadInputOverrides.js?v=20260622-input-override-1';

const INSTALL_FLAG = Symbol.for('pcf-glb-geometry-support-load-input-bridge-v5');
let lastModel = null;

function esc(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function workspaceApi(){return globalThis.__PCF_GLB_GEOMETRY_EXPORT_WORKSPACE__||null;}
function workspaceState(){return workspaceApi()?.state?.()||{};}
function masterData(){return workspaceState().supportLoadMasterData||globalThis.__PCF_GLB_GEOMETRY_SUPPORT_LOAD_MASTERS__?.current?.()||null;}
function objects(){const s=workspaceState();const active=s.activeObjectIds instanceof Set?s.activeObjectIds:new Set(s.activeObjectIds||[]);const src=Array.isArray(s.calculationResolvedObjects)&&s.calculationResolvedObjects.length?s.calculationResolvedObjects:Array.isArray(s.geometryEnrichedObjects)&&s.geometryEnrichedObjects.length?s.geometryEnrichedObjects:s.mapping?.mappedObjects;const list=Array.isArray(src)?src:[];return active.size?list.filter(o=>active.has(o.sourceId||o.id)):list;}
function dlg(){return document.getElementById('geometry-support-load-input-dialog');}
function cell(v){return v===undefined||v===null||v===''?'':esc(v);}
function stateReview(){return workspaceState().supportLoadInputReviewState||{};}
function setReviewState(next){const s=workspaceState();if(s&&typeof s==='object')s.supportLoadInputReviewState=next;}
function store(model){const s=workspaceState();if(s&&typeof s==='object'){s.supportLoadInputModel=model;s.supportLoadHydratedObjects=Array.isArray(model?.hydratedObjects)?model.hydratedObjects:[];}return model;}
function reviewed(model){return applySupportLoadInputReview(model,stateReview());}
function options(){return { supportLoadMasterData: masterData() };}
function buildModel(sourceObjects){return buildGeometrySupportLoadInputModel(sourceObjects,options());}

function summary(m){if(!m)return '<div class="gsli-empty">No pipe-level support-load input hydrator has been run yet.</div>';const ms=m.masterDataSummary||{},as=m.autoSpanSummary||{};return `<div class="gsli-summary"><div><b>${esc(m.pipeCandidateCount)}</b><span>pipe inputs</span></div><div><b>${esc(m.pipeInputReadyCount)}</b><span>ready</span></div><div><b>${esc(m.inputOverrideCount||0)}</b><span>overridden</span></div><div><b>${esc(m.inputLockedCount||0)}</b><span>locked</span></div><div><b>${esc(m.calcReadyPipeInputCount||0)}</b><span>calc-gated</span></div><div><b>${esc(ms.depSpanRowCount??0)}</b><span>DEP rows</span></div><div><b>${esc(as.autoResolvedCount??0)}</b><span>AutoSpan</span></div><div><b>${esc(m.status)}</b><span>status</span></div></div>`;}
function pipeOptions(m){const rows=Array.isArray(m?.pipeInputs)?m.pipeInputs:[];return rows.map(input=>{const key=supportLoadInputReviewKey(input),id=input.identity||{};return `<option value="${esc(key)}">${esc(id.lineNo||id.branchName||key)}</option>`;}).join('');}
function fieldOptions(){return SUPPORT_LOAD_INPUT_OVERRIDE_FIELDS.map(f=>`<option value="${esc(f.path)}">${esc(f.label)} — ${esc(f.path)}</option>`).join('');}
function overrideEditor(m){return `<h4>Reviewed Input Override</h4><div class="gsli-override"><select data-gsli-override-key>${pipeOptions(m)}</select><select data-gsli-override-field>${fieldOptions()}</select><input data-gsli-override-value placeholder="Reviewed value"><input data-gsli-override-reason placeholder="Reason / source"><button type="button" data-gsli-override-apply="true">Apply Override</button><button type="button" data-gsli-override-clear="true">Clear Field Override</button></div><p class="gsli-note">Overrides are controlled reviewer inputs stored before calculation. Controlled LOAD → Masters data and resolved AutoSpan values are audited when used.</p>`;}
function pipeRows(m){const rows=Array.isArray(m?.pipeInputs)?m.pipeInputs.slice(0,160):[];if(!rows.length)return '<div class="gsli-empty">No pipe inputs to show.</div>';return `<h4>Pipe Element Input Attributes</h4><div class="gsli-table-wrap"><table><thead><tr><th>Line</th><th>NPS</th><th>OD</th><th>WT</th><th>ID</th><th>Temp C1</th><th>Temp C2</th><th>Mat dens</th><th>Pipe Wt kg/m</th><th>Fluid OPE kg/m</th><th>Fluid HYD kg/m</th><th>AutoSpan</th><th>DEPSpan</th><th>Round</th><th>Vertical</th><th>Guide</th><th>LineStop</th><th>Override</th><th>Lock</th><th>Calc Gate</th><th>Missing</th></tr></thead><tbody>${rows.map(input=>{const id=input.identity||{},p=input.pipePhysical||{},pr=input.process||{},sp=input.spans||{},fp=input.formulaProfile||{},r=input.readiness||{},ir=input.inputReview||{},oc=Object.keys(input.inputOverrides?.overrides||{}).length;return `<tr class="${r.readyForCalculation?'is-locked':r.status==='INPUT_READY'?'is-ready':r.status==='PARTIAL_INPUT'?'is-partial':'is-blocked'}"><td>${esc(id.lineNo||id.branchName||input.sourceObjectId||'')}</td><td>${cell(id.nps)}</td><td>${cell(id.pipeOdMm)}</td><td>${cell(p.wallThicknessMm)}</td><td>${cell(p.insideDiameterMm)}</td><td>${cell(pr.tempExpC1)}</td><td>${cell(pr.tempExpC2)}</td><td>${cell(p.materialDensityKgM3)}</td><td>${cell(p.unitPipeWtKgPerM)}</td><td>${cell(pr.fluidWtOpeKgPerM)}</td><td>${cell(pr.fluidWtHydKgPerM)}</td><td>${cell(sp.autoSpanMm)}</td><td>${cell(sp.depSpanMm)}</td><td>${cell(fp.roundStep)}</td><td>${esc(r.readyForVertical?'ready':'blocked')}</td><td>${esc(r.readyForGuide?'ready':'blocked')}</td><td>${esc(r.readyForLineStop?'ready':'blocked')}</td><td>${oc?esc(oc+' field(s)'):''}</td><td>${esc(ir.locked?'LOCKED':ir.status||'OPEN')}</td><td>${esc(r.calculationGateStatus||'INPUT_REVIEW_REQUIRED')}</td><td title="${esc((r.missing||[]).join(', '))}">${esc((r.missing||[]).slice(0,3).join(', '))}</td></tr>`;}).join('')}</tbody></table></div>`;}
function supportRows(m){const rows=Array.isArray(m?.rows)?m.rows.slice(0,160):[];if(!rows.length)return '<div class="gsli-empty">No support references to show.</div>';return `<h4>Support → Pipe Input References</h4><div class="gsli-table-wrap"><table><thead><tr><th>Support</th><th>Type</th><th>Tag</th><th>Status</th><th>AutoSpan</th><th>AutoSpan Status</th><th>Associated Pipe</th><th>Line</th><th>Match</th><th>Input Lock</th><th>Calc Gate</th><th>Missing</th></tr></thead><tbody>${rows.map(row=>{const ref=row.input?.supportRef||{},inp=row.input?.pipeSupportLoadInput||{},ir=row.inputReview||inp.inputReview||{};return `<tr class="${row.calculationGateStatus==='INPUT_LOCKED'?'is-locked':row.status==='INPUT_READY'?'is-ready':row.status==='PARTIAL_INPUT'?'is-partial':'is-blocked'}"><td>${esc(row.displayName)}</td><td>${esc(row.supportType)}</td><td>${esc(row.supportTag)}</td><td>${esc(row.status)}</td><td>${cell(ref.autoSpanMm)}</td><td>${esc(ref.autoSpanStatus||'')}</td><td>${esc(ref.associatedPipeId||'')}</td><td>${esc(inp.identity?.lineNo||ref.associatedLineNo||'')}</td><td>${esc(ref.matchMethod||'')}</td><td>${esc(ir.locked?'LOCKED':ir.status||'OPEN')}</td><td>${esc(row.calculationGateStatus||'INPUT_REVIEW_REQUIRED')}</td><td>${esc((row.missingFields||[]).slice(0,3).join(', '))}</td></tr>`;}).join('')}</tbody></table></div>`;}
function render(){const d=dlg();if(!d)return;d.querySelector('[data-gsli-body]').innerHTML=`<div class="gsli-toolbar"><button type="button" data-gsli-build="true">Hydrate Pipe Inputs</button><button type="button" data-gsli-lock="true">Lock Ready Inputs</button><button type="button" data-gsli-unlock="true">Unlock Inputs</button><button type="button" data-gsli-sample="true">Run Sample</button><button type="button" data-gsli-open-master="true">Open Masters</button><button type="button" data-gsli-open-calc="true">Open Calc</button><button type="button" data-gsli-open-enrich="true">Open Enrichment</button><button type="button" data-gsli-export="true">Export Input Model JSON</button><span>${objects().length} active object(s)</span></div><p class="gsli-note">Writes resolved, input-only support-load attributes onto <code>pipe.attributes.supportLoadInput</code>. Hydration uses native/enriched fields first, then controlled LOAD → Masters data and AutoSpan resolver audit.</p>${summary(lastModel)}${overrideEditor(lastModel)}${pipeRows(lastModel)}${supportRows(lastModel)}`;}
function rebuild(){lastModel=reviewed(buildModel(objects()));store(lastModel);render();return lastModel;}
function build(){return rebuild();}
function applyOverride(){if(!lastModel)build();const d=dlg(),key=d?.querySelector('[data-gsli-override-key]')?.value,path=d?.querySelector('[data-gsli-override-field]')?.value,value=d?.querySelector('[data-gsli-override-value]')?.value,reason=d?.querySelector('[data-gsli-override-reason]')?.value;setReviewState(setSupportLoadInputOverride(stateReview(),key,path,value,{reason}));rebuild();}
function clearOverride(){if(!lastModel)build();const d=dlg(),key=d?.querySelector('[data-gsli-override-key]')?.value,path=d?.querySelector('[data-gsli-override-field]')?.value;setReviewState(clearSupportLoadInputOverride(stateReview(),key,path));rebuild();}
function lockInputs(){if(!lastModel)lastModel=reviewed(buildModel(objects()));const next=lockReadySupportLoadInputs(lastModel,stateReview());setReviewState(next);lastModel=applySupportLoadInputReview(lastModel,next);store(lastModel);render();}
function unlockInputs(){if(!lastModel)lastModel=reviewed(buildModel(objects()));const next=unlockSupportLoadInputs(lastModel,stateReview());setReviewState(next);lastModel=applySupportLoadInputReview(lastModel,next);store(lastModel);render();}
function download(){if(!lastModel)build();if(!lastModel)return;const blob=new Blob([JSON.stringify(lastModel,null,2)],{type:'application/json;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='geometry-support-load-input-review-model.json';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function open(){const d=ensure();d.classList.add('is-open');if(!lastModel)build();else render();}
function ensure(){let d=dlg();if(d)return d;d=document.createElement('div');d.id='geometry-support-load-input-dialog';d.className='geometry-support-load-input-dialog';d.innerHTML=`<div class="gsli-card" role="dialog"><div class="gsli-head"><div><b>Pipe-Level Support Load Input Review</b><small>${GEOMETRY_SUPPORT_LOAD_INPUT_VERSION} · ${PIPE_SUPPORT_LOAD_INPUT_SCHEMA} · ${SUPPORT_LOAD_INPUT_REVIEW_VERSION} · ${SUPPORT_LOAD_INPUT_OVERRIDE_VERSION}</small></div><button type="button" data-gsli-close="true">x</button></div><div data-gsli-body></div></div>`;document.body.appendChild(d);d.addEventListener('click',e=>{if(e.target?.closest?.('[data-gsli-close]')){d.classList.remove('is-open');return;}if(e.target?.closest?.('[data-gsli-build]')){build();return;}if(e.target?.closest?.('[data-gsli-lock]')){lockInputs();return;}if(e.target?.closest?.('[data-gsli-unlock]')){unlockInputs();return;}if(e.target?.closest?.('[data-gsli-override-apply]')){applyOverride();return;}if(e.target?.closest?.('[data-gsli-override-clear]')){clearOverride();return;}if(e.target?.closest?.('[data-gsli-sample]')){lastModel=reviewed(buildModel(exampleSupportLoadInputObjects()));store(lastModel);render();return;}if(e.target?.closest?.('[data-gsli-open-master]')){globalThis.__PCF_GLB_GEOMETRY_SUPPORT_LOAD_MASTERS__?.open?.();return;}if(e.target?.closest?.('[data-gsli-open-calc]')){globalThis.__PCF_GLB_GEOMETRY_CALCULATION_CANVAS__?.open?.();return;}if(e.target?.closest?.('[data-gsli-open-enrich]')){globalThis.__PCF_GLB_GEOMETRY_ENRICHMENT__?.open?.();return;}if(e.target?.closest?.('[data-gsli-export]'))download();},true);return d;}
function injectToolbar(root){const section=root?.querySelector?.('.geometry-export-workspace-tool-group');if(!section||section.querySelector('[data-geometry-support-load-input-open]'))return;const b=document.createElement('button');b.type='button';b.className='rvm-tool-btn';b.dataset.geometrySupportLoadInputOpen='true';b.title='Hydrate, override, and lock pipe-level support-load input attributes';b.innerHTML='<span aria-hidden="true">LOAD</span><span>Inputs</span>';section.querySelector('.rvm-ribbon-button-row')?.appendChild(b);}
function styles(){if(document.getElementById('geometry-support-load-input-style'))return;const s=document.createElement('style');s.id='geometry-support-load-input-style';s.textContent='.geometry-support-load-input-dialog{position:fixed;inset:0;display:none;align-items:flex-start;justify-content:center;padding:74px 20px;background:rgba(2,6,23,.56);z-index:12385}.geometry-support-load-input-dialog.is-open{display:flex}.gsli-card{width:min(1440px,calc(100vw - 44px));max-height:calc(100vh - 92px);overflow:auto;background:#0b1424;border:1px solid rgba(126,190,255,.30);border-radius:14px;padding:12px;color:#dbeafe}.gsli-toolbar,.gsli-head,.gsli-override{display:flex;gap:8px;align-items:center;flex-wrap:wrap;justify-content:space-between}.gsli-toolbar,.gsli-override{justify-content:flex-start}.gsli-head b,.gsli-card h4{color:#bfdbfe}.gsli-head small,.gsli-note,.gsli-toolbar span{color:#9fb3cc;font-size:11px}.gsli-head button,.gsli-toolbar button,.gsli-override button,.gsli-override select,.gsli-override input{border:1px solid rgba(126,190,255,.24);border-radius:8px;background:#132238;color:#dbeafe;padding:7px 10px}.gsli-override input{min-width:180px}.gsli-summary{display:grid;grid-template-columns:repeat(8,minmax(0,1fr));gap:8px;margin:8px 0}.gsli-summary div{border:1px solid rgba(126,190,255,.15);border-radius:9px;padding:8px;background:rgba(255,255,255,.035)}.gsli-table-wrap{overflow:auto;max-height:520px}.gsli-table-wrap table{border-collapse:collapse;min-width:100%;font-size:11px}.gsli-table-wrap th,.gsli-table-wrap td{border:1px solid rgba(126,190,255,.13);padding:5px 7px;text-align:left;white-space:nowrap}.gsli-table-wrap th{position:sticky;top:0;background:#132238;color:#bfdbfe}.gsli-table-wrap tr.is-locked td{background:rgba(59,130,246,.10)}.gsli-table-wrap tr.is-ready td{background:rgba(34,197,94,.06)}.gsli-table-wrap tr.is-partial td{background:rgba(245,158,11,.06)}.gsli-table-wrap tr.is-blocked td{background:rgba(239,68,68,.06)}.gsli-empty{padding:16px;border:1px dashed rgba(148,163,184,.22);border-radius:10px;color:#9fb3cc;text-align:center}';document.head.appendChild(s);}
function attach(){const root=document.querySelector('[data-rvm-viewer]');if(!root)return false;injectToolbar(root);return true;}
function click(e){if(!e.target?.closest?.('[data-geometry-support-load-input-open]'))return;e.preventDefault();e.stopPropagation();open();}
export function installGeometrySupportLoadInputBridge(){if(typeof document==='undefined')return;if(globalThis[INSTALL_FLAG])return;globalThis[INSTALL_FLAG]=true;styles();document.addEventListener('click',click,true);let n=0;const wait=()=>{n+=1;if(!attach()&&n<180)setTimeout(wait,300);};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wait,{once:true});else wait();globalThis.addEventListener?.('rvm-model-loaded',()=>setTimeout(wait,320));globalThis.__PCF_GLB_GEOMETRY_SUPPORT_LOAD_INPUTS__={version:GEOMETRY_SUPPORT_LOAD_INPUT_VERSION,schema:GEOMETRY_SUPPORT_LOAD_INPUT_SCHEMA,pipeInputSchema:PIPE_SUPPORT_LOAD_INPUT_SCHEMA,reviewSchema:SUPPORT_LOAD_INPUT_REVIEW_SCHEMA,overrideSchema:SUPPORT_LOAD_INPUT_OVERRIDE_SCHEMA,open,build,lockInputs,unlockInputs,applyOverride,clearOverride,lastModel:()=>lastModel};}
