import { buildSupportLoadQaDashboardModel, SUPPORT_LOAD_QA_DASHBOARD_SCHEMA, SUPPORT_LOAD_QA_DASHBOARD_VERSION } from './GeometrySupportLoadQaDashboard.js?v=20260623-support-load-qa-dashboard-1';

const INSTALL_FLAG = Symbol.for('pcf-glb-support-load-qa-dashboard-bridge-v1');
let lastModel = null;
function esc(v) { return String(v ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;'); }
function state() { return globalThis.__PCF_GLB_GEOMETRY_EXPORT_WORKSPACE__?.state?.() || {}; }
function dialog() { return document.getElementById('geometry-support-load-qa-dialog'); }
function build() { const s = state(); lastModel = buildSupportLoadQaDashboardModel({ inputModel: s.supportLoadInputModel, conflictModel: s.supportLoadConflictModel, formulaResults: s.supportLoadFormulaResults, reportModel: s.supportLoadReportModel }); if (s && typeof s === 'object') s.supportLoadQaDashboard = lastModel; render(); return lastModel; }
function metric(label, value) { return `<div><b>${esc(value)}</b><span>${esc(label)}</span></div>`; }
function summary(m) { if (!m) return '<div class="gslq-empty">Run dashboard after LOAD steps.</div>'; return `<div class="gslq-summary">${metric('inputs', m.input.pipeInputCount)}${metric('ready', m.input.readyCount)}${metric('locked', m.input.lockedCount)}${metric('conflicts', m.conflicts.conflictCount)}${metric('calc rows', m.calculation.calculatedPipeCount)}${metric('blocked', m.calculation.blockedPipeCount)}${metric('reports', m.report.pipeRowCount)}${metric('status', m.status)}</div>`; }
function actions(m) { const rows = Array.isArray(m?.nextActions) ? m.nextActions : []; return rows.length ? `<h4>Next Actions</h4><ol>${rows.map(row => `<li>${esc(row)}</li>`).join('')}</ol>` : '<div class="gslq-ready">QA dashboard has no blocking action.</div>'; }
function details(m) { if (!m) return ''; const rows = [['Input status', m.input.status], ['Missing input fields', m.input.missingFieldCount], ['Overrides', m.input.overrideCount], ['AutoSpan resolved', m.input.autoSpanResolvedCount], ['Conflict status', m.conflicts.status], ['High severity conflicts', m.conflicts.highSeverityCount], ['Calculation status', m.calculation.status], ['Input mutations', m.calculation.inputMutationCount], ['Stale results cleared', m.calculation.staleClearedCount], ['Report status', m.report.status]]; return `<h4>QA Detail</h4><div class="gslq-table-wrap"><table><tbody>${rows.map(([k,v]) => `<tr><th>${esc(k)}</th><td>${esc(v)}</td></tr>`).join('')}</tbody></table></div>`; }
function render() { const d = dialog(); if (!d) return; d.querySelector('[data-gslq-body]').innerHTML = `<div class="gslq-toolbar"><button type="button" data-gslq-refresh="true">Refresh QA</button><button type="button" data-gslq-inputs="true">Open Inputs</button><button type="button" data-gslq-conflicts="true">Open Conflicts</button><button type="button" data-gslq-calc="true">Open Calc</button><button type="button" data-gslq-report="true">Open Report</button><button type="button" data-gslq-export="true">Export QA JSON</button></div><p class="gslq-note">Read-only QA dashboard. It summarizes input hydration, conflicts, locking, calculation, report readiness, and writeback audit. It does not hydrate, calculate, or mutate fields.</p>${summary(lastModel)}${actions(lastModel)}${details(lastModel)}`; }
function download() { if (!lastModel) build(); const blob = new Blob([JSON.stringify(lastModel, null, 2)], { type: 'application/json;charset=utf-8' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'support-load-qa-dashboard.json'; document.body.appendChild(a); a.click(); a.remove(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
function ensure() { let d = dialog(); if (d) return d; d = document.createElement('div'); d.id = 'geometry-support-load-qa-dialog'; d.className = 'geometry-support-load-qa-dialog'; d.innerHTML = `<div class="gslq-card" role="dialog"><div class="gslq-head"><div><b>Support Load QA Dashboard</b><small>${SUPPORT_LOAD_QA_DASHBOARD_VERSION} · ${SUPPORT_LOAD_QA_DASHBOARD_SCHEMA}</small></div><button type="button" data-gslq-close="true">x</button></div><div data-gslq-body></div></div>`; document.body.appendChild(d); d.addEventListener('click', e => { if (e.target?.closest?.('[data-gslq-close]')) { d.classList.remove('is-open'); return; } if (e.target?.closest?.('[data-gslq-refresh]')) { build(); return; } if (e.target?.closest?.('[data-gslq-inputs]')) { globalThis.__PCF_GLB_GEOMETRY_SUPPORT_LOAD_INPUTS__?.open?.(); return; } if (e.target?.closest?.('[data-gslq-conflicts]')) { globalThis.__PCF_GLB_GEOMETRY_SUPPORT_LOAD_CONFLICTS__?.open?.(); return; } if (e.target?.closest?.('[data-gslq-calc]')) { globalThis.__PCF_GLB_GEOMETRY_SUPPORT_LOAD_FORMULAS__?.open?.(); return; } if (e.target?.closest?.('[data-gslq-report]')) { globalThis.__PCF_GLB_GEOMETRY_SUPPORT_LOAD_REPORTS__?.open?.(); return; } if (e.target?.closest?.('[data-gslq-export]')) download(); }, true); return d; }
function open() { const d = ensure(); d.classList.add('is-open'); if (!lastModel) build(); else render(); }
function injectToolbar(root) { const section = root?.querySelector?.('.geometry-export-workspace-tool-group'); if (!section || section.querySelector('[data-geometry-support-load-qa-open]')) return; const b = document.createElement('button'); b.type = 'button'; b.className = 'rvm-tool-btn'; b.dataset.geometrySupportLoadQaOpen = 'true'; b.title = 'Support-load QA dashboard'; b.innerHTML = '<span aria-hidden="true">LOAD</span><span>QA</span>'; section.querySelector('.rvm-ribbon-button-row')?.appendChild(b); }
function styles() { if (document.getElementById('geometry-support-load-qa-style')) return; const s = document.createElement('style'); s.id = 'geometry-support-load-qa-style'; s.textContent = '.geometry-support-load-qa-dialog{position:fixed;inset:0;display:none;align-items:flex-start;justify-content:center;padding:74px 20px;background:rgba(2,6,23,.56);z-index:12395}.geometry-support-load-qa-dialog.is-open{display:flex}.gslq-card{width:min(1260px,calc(100vw - 44px));max-height:calc(100vh - 92px);overflow:auto;background:#0b1424;border:1px solid rgba(34,197,94,.30);border-radius:14px;padding:12px;color:#dbeafe}.gslq-toolbar,.gslq-head{display:flex;gap:8px;align-items:center;flex-wrap:wrap;justify-content:space-between}.gslq-toolbar{justify-content:flex-start}.gslq-head b,.gslq-card h4{color:#bbf7d0}.gslq-head small,.gslq-note{color:#9fb3cc;font-size:11px}.gslq-head button,.gslq-toolbar button{border:1px solid rgba(34,197,94,.25);border-radius:8px;background:#092216;color:#bbf7d0;padding:7px 10px}.gslq-summary{display:grid;grid-template-columns:repeat(8,minmax(0,1fr));gap:8px;margin:8px 0}.gslq-summary div{border:1px solid rgba(34,197,94,.18);border-radius:9px;padding:8px;background:rgba(255,255,255,.04)}.gslq-summary b{display:block;font-size:18px;color:#fff}.gslq-summary span{font-size:11px;color:#9fb3cc}.gslq-table-wrap table{border-collapse:collapse;width:100%;font-size:12px}.gslq-table-wrap th,.gslq-table-wrap td{border:1px solid rgba(255,255,255,.08);padding:7px;text-align:left}.gslq-empty,.gslq-ready{padding:16px;border:1px dashed rgba(148,163,184,.22);border-radius:10px;color:#9fb3cc}.gslq-ready{color:#bbf7d0;border-color:rgba(34,197,94,.25)}'; document.head.appendChild(s); }
export function installGeometrySupportLoadQaDashboardBridge() { if (globalThis[INSTALL_FLAG]) return globalThis.__PCF_GLB_GEOMETRY_SUPPORT_LOAD_QA__; globalThis[INSTALL_FLAG] = true; styles(); globalThis.__PCF_GLB_GEOMETRY_SUPPORT_LOAD_QA__ = Object.freeze({ open, build: () => build(), current: () => lastModel }); document.addEventListener('click', e => { if (e.target?.closest?.('[data-geometry-support-load-qa-open]')) open(); }, true); const mo = new MutationObserver(records => { for (const record of records) for (const node of record.addedNodes || []) if (node?.querySelector) injectToolbar(node); }); mo.observe(document.documentElement, { childList: true, subtree: true }); injectToolbar(document); return globalThis.__PCF_GLB_GEOMETRY_SUPPORT_LOAD_QA__; }
