import {
  buildDefaultSupportLoadMasterData,
  normalizeSupportLoadMasterDataPackage,
  findDepSpanMasterRow,
  summarizeSupportLoadMasterData
} from './GeometrySupportLoadMasterData.js?v=20260623-support-load-master-data-1';
import {
  resolveSupportLoadAutoSpansForPipe,
  summarizeSupportLoadAutoSpans,
  SUPPORT_LOAD_AUTOSPAN_RESOLVER_VERSION
} from './GeometrySupportLoadAutoSpanResolver.js?v=20260623-support-load-autospan-resolver-1';

export const GEOMETRY_SUPPORT_LOAD_INPUT_SCHEMA = 'geometry-support-load-input-model/v1';
export const PIPE_SUPPORT_LOAD_INPUT_SCHEMA = 'support-load-input/v1';
export const SUPPORT_LOAD_INPUT_REF_SCHEMA = 'support-load-input-ref/v1';
export const GEOMETRY_SUPPORT_LOAD_INPUT_VERSION = '20260623-autospan-resolver-1';
export const SUPPORT_LOAD_INPUT_MODULE_ID = 'support-load-input-model/v1';
export const SUPPORT_LOAD_INPUT_REQUIRED_FIELDS = Object.freeze([
  'pipe.attributes.supportLoadInput.identity.nps',
  'pipe.attributes.supportLoadInput.identity.pipeOdMm',
  'pipe.attributes.supportLoadInput.pipePhysical.wallThicknessMm',
  'pipe.attributes.supportLoadInput.pipePhysical.unitPipeWtKgPerM',
  'pipe.attributes.supportLoadInput.process.tempExpC1',
  'pipe.attributes.supportLoadInput.process.fluidWtOpeKgPerM',
  'pipe.attributes.supportLoadInput.process.fluidWtHydKgPerM',
  'pipe.attributes.supportLoadInput.spans.autoSpanMm or pipe.attributes.supportLoadInput.spans.depSpanMm'
]);
const MAX_OBJECTS = 20000;
function text(value) { return String(value ?? '').trim(); }
function norm(value) { return text(value).toUpperCase().replace(/[^A-Z0-9.]+/g, ''); }
function num(value) { if (typeof value === 'number') return Number.isFinite(value) ? value : null; const match = text(value).replace(/,/g, '').match(/[-+]?\d*\.?\d+(?:e[-+]?\d+)?/i); if (!match) return null; const n = Number(match[0]); return Number.isFinite(n) ? n : null; }
function round3(value) { return Number.isFinite(value) ? Math.round(value * 1000) / 1000 : null; }
function rawFields(object) { return { ...(object?.rawRecord?.rawFields || {}), ...(object?.rawFields || {}) }; }
function rawValue(raw, keys) { const entries = Object.entries(raw || {}); for (const key of keys) { if (text(raw[key])) return raw[key]; const match = entries.find(([name, value]) => norm(name) === norm(key) && text(value)); if (match) return match[1]; } return undefined; }
function firstNumber(...values) { for (const value of values) { const n = num(value); if (n !== null) return n; } return null; }
function point(value) { const x = num(value?.x), y = num(value?.y), z = num(value?.z); return x === null || y === null || z === null ? null : Object.freeze({ x, y, z }); }
function centerOf(object) { return point(object?.geometry?.center) || point(object?.geometryEnrichment?.geometry?.center) || point(object?.rawRecord?.geometry?.center); }
function distance(a, b) { return a && b ? Math.hypot(a.x - b.x, a.y - b.y, a.z - b.z) : Infinity; }
function objectId(object) { return text(object?.sourceId || object?.id || object?.canonicalId || object?.displayName); }
function family(object) { return text(object?.family || object?.objectType || object?.rawRecord?.objectClass || object?.rawRecord?.objectType).toUpperCase(); }
function isRejected(object) { return text(object?.mappingStatus).toUpperCase() === 'REJECTED'; }
function isPipe(object) { const raw = rawFields(object); return family(object) === 'PIPE' || norm(raw.TYPE).includes('PIPE') || norm(object?.primitiveKind).includes('PIPE'); }
function isSupport(object) { const raw = rawFields(object); return family(object) === 'SUPPORT' || family(object) === 'ATTA' || norm(raw.TYPE).includes('ATTA') || norm(object?.displayName).includes('SUPPORT'); }
function lineKey(object) { return text(object?.geometryEnrichment?.branch?.lineKey || object?.enrichedFields?.lineKey || object?.lineNo || rawFields(object).LINE_NO); }
function branchName(object) { return text(object?.geometryEnrichment?.branch?.branchName || object?.enrichedFields?.branchName || object?.rawRecord?.sourcePath || object?.sourcePath); }
function npsFromLine(value) { const match = text(value).match(/(^|[^0-9.])(\d+(?:\.\d+)?)\s*[\"]/); return match ? num(match[2]) : null; }
function audit(source, field, value, extra = {}) { return Object.freeze({ source, field, value, ...extra }); }
function materialKeys(...values) { return values.map(norm).filter(Boolean); }
function masterDataFrom(options = {}) { return normalizeSupportLoadMasterDataPackage(options.supportLoadMasterData || buildDefaultSupportLoadMasterData()); }
function npsFromOd(od, masterData) { if (od === null) return null; let best = null; for (const row of masterData.depSpanRows || []) { const rowOd = num(row.pipeOdMm); if (rowOd === null) continue; const delta = Math.abs(rowOd - od); if (delta <= 1.5 && (!best || delta < best.delta)) best = { ...row, delta }; } return best?.nps ?? null; }
function depFor(nps, od, masterData) { return findDepSpanMasterRow(masterData, { nps, pipeOdMm: od }); }
function matchMaterialDensity(masterData, { materialCategory, materialCode, material }) { const keys = materialKeys(materialCategory, materialCode, material); if (!keys.length) return null; return (masterData.materialDensityRows || []).find(row => materialKeys(row.materialCategory, row.materialCode, row.materialName).some(key => keys.includes(key))) || null; }
function matchPipeWeight(masterData, { nps, od, wall, schedule }) { let best = null; for (const row of masterData.pipeWeightRows || []) { let score = 0; if (nps !== null && num(row.nps) !== null && Math.abs(num(row.nps) - nps) < 0.0001) score += 5; if (od !== null && num(row.pipeOdMm) !== null && Math.abs(num(row.pipeOdMm) - od) <= 1.5) score += 4; if (wall !== null && num(row.wallThicknessMm) !== null && Math.abs(num(row.wallThicknessMm) - wall) <= 0.25) score += 3; if (text(schedule) && norm(row.schedule) === norm(schedule)) score += 2; if (score && (!best || score > best.score)) best = { row, score }; } return best?.row || null; }
function firstHydroProfile(masterData) { return (masterData.hydroDensityProfiles || []).find(row => num(row.fluidDensityHydKgM3) !== null) || null; }
function firstRoundingProfile(masterData) { return (masterData.roundingProfiles || []).find(row => num(row.roundStep) !== null) || null; }
function firstTempProfile(masterData) { return (masterData.tempFunctionProfiles || []).find(row => text(row.profileId)) || null; }
function resolvePipeSource(object, options = {}) {
  const masterData = masterDataFrom(options); const raw = rawFields(object); const enrichment = object?.geometryEnrichment || {};
  const od = firstNumber(object?.pipe?.odMm, enrichment.branch?.boreMm, rawValue(raw, ['PipeOD', 'PIPE_OD', 'OD_MM', 'OD', 'DIA', 'DIAMETER', 'BORE']));
  const nps = firstNumber(object?.pipe?.nps, object?.nps, rawValue(raw, ['NS', 'NPS', 'NOMINAL_SIZE', 'PIPE_SIZE']), npsFromLine(lineKey(object) || branchName(object)), npsFromOd(od, masterData));
  const wall = firstNumber(enrichment.piping?.wallThicknessMm, object?.pipe?.wallThicknessMm, rawValue(raw, ['WALL_THICK', 'WALL_THICKNESS_MM', 'WT_MM', 'THK_MM']));
  const insideDiameter = od !== null && wall !== null ? round3(od - 2 * wall) : null;
  const schedule = text(enrichment.piping?.schedule || object?.pipe?.schedule || rawValue(raw, ['SCHEDULE', 'SCH']));
  const material = text(enrichment.piping?.materialName || object?.pipe?.material || rawValue(raw, ['MATERIAL', 'MAT']));
  const materialCode = text(enrichment.piping?.materialCode || object?.pipe?.materialCode || rawValue(raw, ['MATERIAL_CODE', 'MATID']));
  const materialCategory = text(object?.pipe?.materialCategory || rawValue(raw, ['Mat_Category', 'MAT_CATEGORY']));
  const auditRows = [];
  const materialRow = matchMaterialDensity(masterData, { materialCategory, materialCode, material });
  const nativeDensity = firstNumber(object?.pipe?.materialDensityKgM3, rawValue(raw, ['MATERIAL_DENSITY_KG_M3']));
  const materialDensity = firstNumber(nativeDensity, materialRow?.materialDensityKgM3);
  if (nativeDensity === null && materialRow) auditRows.push(audit('PROJECT_MASTER_TABLE', 'pipePhysical.materialDensityKgM3', materialDensity, { table: 'materialDensityRows', materialCategory: materialRow.materialCategory || materialCategory }));
  const pipeWeightRow = matchPipeWeight(masterData, { nps, od, wall, schedule });
  const nativePipeWeight = firstNumber(object?.pipe?.unitPipeWtKgPerM, object?.pipe?.weightKgM, rawValue(raw, ['UnitPipewtKg/m', 'UNIT_PIPE_WT_KG_M', 'PIPE_WT_KG_M', 'WEIGHT_KG_M']));
  let pipeWeight = firstNumber(nativePipeWeight, pipeWeightRow?.unitPipeWtKgPerM);
  if (nativePipeWeight === null && pipeWeightRow) auditRows.push(audit('PROJECT_MASTER_TABLE', 'pipePhysical.unitPipeWtKgPerM', pipeWeight, { table: 'pipeWeightRows', match: { nps: pipeWeightRow.nps, pipeOdMm: pipeWeightRow.pipeOdMm, schedule: pipeWeightRow.schedule } }));
  if (pipeWeight === null && od !== null && insideDiameter !== null && materialDensity !== null) { pipeWeight = round3(Math.PI / 4 * (od ** 2 - insideDiameter ** 2) * 1e-6 * materialDensity); auditRows.push(audit('DERIVED_PIPE_WEIGHT', 'pipePhysical.unitPipeWtKgPerM', pipeWeight, { expression: 'PI/4*(OD^2-ID^2)*1e-6*materialDensityKgM3' })); }
  const temp1 = firstNumber(enrichment.process?.temperature1C, object?.process?.temperature1C, object?.process?.temperatureC, rawValue(raw, ['TEMP_EXP_C1', 'TEMP_C1', 'DESIGN_TEMP_C']));
  const temp2 = firstNumber(enrichment.process?.temperature2C, object?.process?.temperature2C, rawValue(raw, ['TEMP_EXP_C2', 'TEMP_C2']));
  const densityOpe = firstNumber(enrichment.process?.fluidDensityKgM3, object?.process?.fluidDensityOpeKgM3, object?.process?.fluidDensityKgM3, rawValue(raw, ['FLUID_DENSITY_OPE_KG_M3', 'DENSITY_MIXED', 'DENSITY']));
  const hydroRow = firstHydroProfile(masterData); const densityHydNative = firstNumber(object?.process?.fluidDensityHydKgM3, object?.process?.hydroFluidDensityKgM3, rawValue(raw, ['FLUID_DENSITY_HYD_KG_M3', 'HYD_DENSITY_KG_M3', 'HYDRO_DENSITY'])); const densityHyd = firstNumber(densityHydNative, hydroRow?.fluidDensityHydKgM3);
  if (densityHydNative === null && hydroRow) auditRows.push(audit('PROJECT_MASTER_TABLE', 'process.fluidDensityHydKgM3', densityHyd, { table: 'hydroDensityProfiles', profileId: hydroRow.profileId }));
  let fluidOpe = firstNumber(object?.process?.fluidWtOpeKgPerM, rawValue(raw, ['FluidwtKg/m', 'FLUID_WT_OPE_KG_M', 'FLUIDWT_KG_M'])); let fluidHyd = firstNumber(object?.process?.fluidWtHydKgPerM, rawValue(raw, ['FLUID_WT_HYD_KG_M', 'HYD_FLUIDWT_KG_M']));
  if (fluidOpe === null && insideDiameter !== null && densityOpe !== null) { fluidOpe = round3(Math.PI / 4 * insideDiameter ** 2 * 1e-6 * densityOpe); auditRows.push(audit('DERIVED_FLUID_WEIGHT', 'process.fluidWtOpeKgPerM', fluidOpe, { expression: 'PI/4*ID^2*1e-6*fluidDensityOpeKgM3' })); }
  if (fluidHyd === null && insideDiameter !== null && densityHyd !== null) { fluidHyd = round3(Math.PI / 4 * insideDiameter ** 2 * 1e-6 * densityHyd); auditRows.push(audit('DERIVED_FLUID_WEIGHT', 'process.fluidWtHydKgPerM', fluidHyd, { expression: 'PI/4*ID^2*1e-6*fluidDensityHydKgM3' })); }
  const depRaw = firstNumber(object?.spans?.depSpanMm, rawValue(raw, ['DEP SPAN', 'DEP_SPAN', 'DEPSPAN', 'DEPSPAN_MM'])); const depLookup = depRaw === null ? depFor(nps, od, masterData) : null; const roundingProfile = firstRoundingProfile(masterData); const tempProfile = firstTempProfile(masterData);
  return { raw, enrichment, masterData, masterDataSummary: summarizeSupportLoadMasterData(masterData), nps, od, wall, insideDiameter, schedule, material, materialCode, materialCategory, materialDensity, pipeWeight, temp1, temp2, densityOpe, densityHyd, fluidOpe, fluidHyd, autoSpan: firstNumber(object?.spans?.autoSpanMm, rawValue(raw, ['AutoSpan', 'AUTOSPAN_MM', 'AUTO_SPAN_MM'])), depSpan: depRaw ?? depLookup?.depSpanMm ?? null, depLookup, roundingProfile, tempProfile, auditRows };
}
function readiness(input) { const identity = input.identity, pipe = input.pipePhysical, process = input.process, spans = input.spans; const hasSpan = spans.autoSpanMm !== null || spans.depSpanMm !== null; const ope = pipe.unitPipeWtKgPerM !== null && process.fluidWtOpeKgPerM !== null && hasSpan; const hyd = pipe.unitPipeWtKgPerM !== null && process.fluidWtHydKgPerM !== null && hasSpan; const lineStop = identity.pipeOdMm !== null && pipe.wallThicknessMm !== null && process.tempExpC1 !== null; const guide = ope && pipe.wallThicknessMm !== null && process.tempExpC1 !== null; const missing = []; for (const [field, ok] of [['identity.nps', identity.nps !== null], ['identity.pipeOdMm', identity.pipeOdMm !== null], ['pipePhysical.wallThicknessMm', pipe.wallThicknessMm !== null], ['pipePhysical.unitPipeWtKgPerM', pipe.unitPipeWtKgPerM !== null], ['process.tempExpC1', process.tempExpC1 !== null], ['process.fluidWtOpeKgPerM', process.fluidWtOpeKgPerM !== null], ['process.fluidWtHydKgPerM', process.fluidWtHydKgPerM !== null], ['spans.autoSpanMm or spans.depSpanMm', hasSpan]]) if (!ok) missing.push(field); return Object.freeze({ readyForVertical: ope && hyd, readyForOpeVertical: ope, readyForHydVertical: hyd, readyForGuide: guide, readyForLineStop: lineStop, missing: Object.freeze(missing), status: !missing.length ? 'INPUT_READY' : lineStop ? 'PARTIAL_INPUT' : 'BLOCKED' }); }
export function buildPipeSupportLoadInput(object, options = {}) {
  const source = resolvePipeSource(object, options); const line = lineKey(object) || text(object?.lineNo); const profile = Object.freeze({ profileId: 'ACCESS_TEMP_WALL_WEIGHTED_V1', gravityFactor: 10, verticalLoadFactor: 1.1, roundMajor: source.roundingProfile?.roundMajor ?? 100, roundStep: source.roundingProfile?.roundStep ?? 50, roundMode: source.roundingProfile?.roundMode || 'up', tempFunctionProfileId: source.tempProfile?.profileId || 'TEMP_FNC_IDENTITY', noLoadFormula: true });
  const input = { schema: PIPE_SUPPORT_LOAD_INPUT_SCHEMA, version: GEOMETRY_SUPPORT_LOAD_INPUT_VERSION, sourceObjectId: objectId(object), identity: Object.freeze({ lineNo: line, branchKey: lineKey(object), branchName: branchName(object), nps: source.nps, pipeOdMm: source.od }), pipePhysical: Object.freeze({ wallThicknessMm: source.wall, insideDiameterMm: source.insideDiameter, schedule: source.schedule, material: source.material, materialCode: source.materialCode, materialCategory: source.materialCategory, materialDensityKgM3: source.materialDensity, insulationThicknessMm: firstNumber(source.enrichment.process?.insulationThicknessMm, object?.pipe?.insulationThicknessMm, rawValue(source.raw, ['INSUL_THICK', 'INSULATION_THICKNESS_MM'])), unitPipeWtKgPerM: source.pipeWeight }), process: Object.freeze({ tempExpC1: source.temp1, tempExpC2: source.temp2, fluidDensityOpeKgM3: source.densityOpe, fluidDensityHydKgM3: source.densityHyd, fluidWtOpeKgPerM: source.fluidOpe, fluidWtHydKgPerM: source.fluidHyd }), spans: Object.freeze({ autoSpanMm: source.autoSpan, depSpanMm: source.depSpan, autoSpanBySupport: Object.freeze({}) }), formulaProfile: profile, supportRefs: Object.freeze([]), audit: Object.freeze([audit('PIPE_SUPPORT_LOAD_INPUT_HYDRATOR', 'pipe.attributes.supportLoadInput', objectId(object)), audit('SUPPORT_LOAD_MASTER_DATA', 'supportLoadMasterData', source.masterDataSummary.status, source.masterDataSummary), ...(source.depLookup ? [audit('PROJECT_MASTER_TABLE', 'spans.depSpanMm', source.depLookup.depSpanMm, { table: 'depSpanRows', nps: source.depLookup.nps, pipeOdMm: source.depLookup.pipeOdMm })] : []), ...(source.roundingProfile ? [audit('PROJECT_MASTER_TABLE', 'formulaProfile.rounding', profile.roundStep, { table: 'roundingProfiles', profileId: source.roundingProfile.profileId })] : []), ...(source.tempProfile ? [audit('PROJECT_MASTER_TABLE', 'formulaProfile.tempFunction', profile.tempFunctionProfileId, { table: 'tempFunctionProfiles' })] : []), ...source.auditRows]) };
  return Object.freeze({ ...input, readiness: readiness(input) });
}
function withPipeInput(pipe, input, refs = []) { const autoSpanBySupport = {}; const autoValues = []; for (const ref of refs) { if (ref.autoSpanMm !== null && ref.autoSpanMm !== undefined) { autoSpanBySupport[ref.supportTag || ref.supportId] = ref.autoSpanMm; autoValues.push(ref.autoSpanMm); } } const resolvedAuto = input.spans.autoSpanMm ?? (autoValues.length ? round3(Math.max(...autoValues)) : null); const autoAudit = refs.flatMap(ref => Array.isArray(ref.autoSpanAudit) ? ref.autoSpanAudit : []); const staged = { ...input, supportRefs: Object.freeze(refs), spans: Object.freeze({ ...input.spans, autoSpanMm: resolvedAuto, autoSpanBySupport: Object.freeze(autoSpanBySupport) }), audit: Object.freeze([...(input.audit || []), ...autoAudit]) }; const next = Object.freeze({ ...staged, readiness: readiness(staged) }); return Object.freeze({ ...pipe, attributes: Object.freeze({ ...(pipe.attributes || {}), supportLoadInput: next }), supportLoadInput: next }); }
function supportDetails(support) { const raw = rawFields(support); return { supportType: text(support?.support?.supportType || raw.SUPPORT_KIND || raw.SUPPORT_TYPE || 'GENERIC_SUPPORT'), supportTag: text(support?.support?.supportTag || raw.REF || raw.PS || raw.SUPPORT_TAG), attachedPipeOdMm: firstNumber(support?.pipe?.odMm, raw.ATTACHED_PIPE_OD), autoSpanMm: firstNumber(support?.spans?.autoSpanMm, rawValue(raw, ['AutoSpan', 'AUTOSPAN_MM', 'AUTO_SPAN_MM'])) }; }
function bestPipeForSupport(support, pipes) { let best = null; const details = supportDetails(support); for (const pipe of pipes) { const input = pipe.attributes?.supportLoadInput || buildPipeSupportLoadInput(pipe); let score = 0; const reasons = []; if (norm(lineKey(support)) && norm(lineKey(support)) === norm(input.identity.branchKey || input.identity.lineNo)) { score += 8; reasons.push('line-key'); } if (details.attachedPipeOdMm !== null && input.identity.pipeOdMm !== null && Math.abs(details.attachedPipeOdMm - input.identity.pipeOdMm) <= 1) { score += 3; reasons.push('attached-od'); } const d = distance(centerOf(support), centerOf(pipe)); if (Number.isFinite(d) && d <= Math.max(300, (input.identity.pipeOdMm || 100) * 4)) { score += 2; reasons.push('nearest-center'); } if (score && (!best || score > best.score || (score === best.score && (d ?? Infinity) < (best.distanceMm ?? Infinity)))) best = { pipe, score, distanceMm: Number.isFinite(d) ? round3(d) : null, reasons }; } return best; }
function supportRef(support, match) { const details = supportDetails(support); const input = match?.pipe?.attributes?.supportLoadInput || null; return Object.freeze({ schema: SUPPORT_LOAD_INPUT_REF_SCHEMA, supportId: objectId(support), supportTag: details.supportTag, supportType: details.supportType, associatedPipeId: match?.pipe ? objectId(match.pipe) : '', associatedLineNo: input?.identity?.lineNo || '', matchMethod: match?.reasons?.join('+') || 'none', matchScore: match?.score || 0, distanceMm: match?.distanceMm ?? null, autoSpanMm: details.autoSpanMm, review: Object.freeze({ associationStatus: match ? 'AUTO_MATCHED' : 'NO_PIPE_MATCH', reviewerLocked: false }) }); }
export function hydratePipeSupportLoadInputs(mappedObjects = [], options = {}) { const objects = (Array.isArray(mappedObjects) ? mappedObjects : []).slice(0, MAX_OBJECTS).filter(object => object && !isRejected(object)); const pipes = objects.filter(isPipe).map(pipe => withPipeInput(pipe, buildPipeSupportLoadInput(pipe, options))); const refs = new Map(); const matches = new Map(); const supports = objects.filter(isSupport); const supportById = new Map(supports.flatMap(support => [[objectId(support), support], [supportDetails(support).supportTag, support]])); for (const support of supports) { const match = bestPipeForSupport(support, pipes); matches.set(objectId(support), match); if (match?.pipe) { const pipeId = objectId(match.pipe); if (!refs.has(pipeId)) refs.set(pipeId, []); refs.get(pipeId).push(supportRef(support, match)); } } const finalPipes = pipes.map(pipe => { const pipeRefs = refs.get(objectId(pipe)) || []; const resolvedRefs = resolveSupportLoadAutoSpansForPipe(pipe, pipeRefs, supportById); return withPipeInput(pipe, pipe.attributes.supportLoadInput, resolvedRefs); }); const byId = new Map(finalPipes.map(pipe => [objectId(pipe), pipe])); const finalObjects = objects.map(object => isPipe(object) ? byId.get(objectId(object)) || object : isSupport(object) ? Object.freeze({ ...object, attributes: Object.freeze({ ...(object.attributes || {}), supportLoadInputRef: (byId.get(objectId(matches.get(objectId(object))?.pipe))?.attributes?.supportLoadInput?.supportRefs || []).find(ref => ref.supportId === objectId(object)) || supportRef(object, matches.get(objectId(object))) }) }) : object); return Object.freeze({ objects: Object.freeze(finalObjects), pipes: Object.freeze(finalPipes), supports: Object.freeze(finalObjects.filter(isSupport)) }); }
function rowForSupport(support, pipe) { const ref = support.attributes?.supportLoadInputRef || supportRef(support, null); const input = pipe?.attributes?.supportLoadInput || null; const missing = input ? (input.readiness.missing || []).map(field => `pipe.attributes.supportLoadInput.${field}`) : ['pipe.attributes.supportLoadInput']; const warnings = []; if (!pipe) warnings.push('no-associated-pipe-candidate'); if (ref.autoSpanStatus && String(ref.autoSpanStatus).startsWith('REVIEW_REQUIRED')) warnings.push(`autospan:${ref.autoSpanStatus}`); if (missing.length) warnings.push(`missing-required-fields:${missing.join('|')}`); return Object.freeze({ schemaVersion: 'support-load-input-row/v1', objectId: objectId(support), displayName: text(support.displayName || support.id), family: 'SUPPORT', supportType: ref.supportType, supportTag: ref.supportTag, status: input?.readiness?.status || 'BLOCKED', missingFields: Object.freeze(missing), optionalPresent: Object.freeze([]), warnings: Object.freeze(warnings), input: Object.freeze({ supportRef: ref, pipeSupportLoadInput: input }), audit: Object.freeze([{ source: 'SUPPORT_LOAD_INPUT_MODEL', field: 'pipe.attributes.supportLoadInput', objectId: ref.associatedPipeId, status: input?.readiness?.status || 'missing' }, { source: 'SUPPORT_LOAD_INPUT_MODEL', field: 'noLoadFormula', value: true }]) }); }
export function buildGeometrySupportLoadInputModel(mappedObjects = [], options = {}) { const hydrated = hydratePipeSupportLoadInputs(mappedObjects, options); const rows = hydrated.supports.map(support => { const pipeId = support.attributes?.supportLoadInputRef?.associatedPipeId; return rowForSupport(support, hydrated.pipes.find(pipe => objectId(pipe) === pipeId)); }); const pipeReady = hydrated.pipes.filter(pipe => pipe.attributes.supportLoadInput.readiness.status === 'INPUT_READY').length; const pipePartial = hydrated.pipes.filter(pipe => pipe.attributes.supportLoadInput.readiness.status === 'PARTIAL_INPUT').length; const pipeBlocked = hydrated.pipes.length - pipeReady - pipePartial; const ready = rows.filter(row => row.status === 'INPUT_READY').length; const blocked = rows.filter(row => row.status === 'BLOCKED').length; const masterData = masterDataFrom(options); return Object.freeze({ schemaVersion: GEOMETRY_SUPPORT_LOAD_INPUT_SCHEMA, pipeInputSchema: PIPE_SUPPORT_LOAD_INPUT_SCHEMA, version: GEOMETRY_SUPPORT_LOAD_INPUT_VERSION, autoSpanResolverVersion: SUPPORT_LOAD_AUTOSPAN_RESOLVER_VERSION, moduleId: SUPPORT_LOAD_INPUT_MODULE_ID, displayName: 'Pipe-Level Support Load Input Hydrator', evaluatedAt: options.evaluatedAt || new Date().toISOString(), objectCount: rows.length, pipeCandidateCount: hydrated.pipes.length, pipeInputReadyCount: pipeReady, pipeInputPartialCount: pipePartial, pipeInputBlockedCount: pipeBlocked, readyCount: ready, partialCount: rows.length - ready - blocked, blockedCount: blocked, status: blocked || pipeBlocked ? 'BLOCKED' : rows.length || hydrated.pipes.length ? 'INPUT_READY' : 'EMPTY', requiredFields: SUPPORT_LOAD_INPUT_REQUIRED_FIELDS, masterDataSummary: summarizeSupportLoadMasterData(masterData), autoSpanSummary: summarizeSupportLoadAutoSpans(hydrated.pipes), hydratedObjects: hydrated.objects, pipeInputs: Object.freeze(hydrated.pipes.map(pipe => pipe.attributes.supportLoadInput)), rows: Object.freeze(rows), noLoadFormula: true, assumptions: Object.freeze(['This model writes resolved support-load inputs onto pipe.attributes.supportLoadInput before any formula engine can run.', 'Support rows are references only; support-load formulas must later read pipe.attributes.supportLoadInput.', 'Controlled support-load master data may hydrate missing inputs, but use is audited as PROJECT_MASTER_TABLE.', 'AutoSpan may be resolved only from associated support coordinates; unresolved spans remain review-required.', 'This phase does not calculate support loads and writes no OPE/HYD/Guide/LineStop result fields.']) }); }
export function exampleSupportLoadInputObjects() { return [ { id: 'PIPE-8-P25168', family: 'PIPE', lineNo: '8"-P25168-61502-01', displayName: 'PIPE 8"-P25168-61502-01', rawFields: { NS: 8, PipeOD: 219.075, WALL_THICK: 12.7, TEMP_EXP_C1: 100, TEMP_EXP_C2: 59 }, geometry: { center: { x: 0, y: 0, z: 0 } }, pipe: { odMm: 219.075, wallThicknessMm: 12.7, materialCategory: 'LT' }, process: { fluidDensityKgM3: 800, temperature1C: 100 } }, { id: 'SUP-PS-001', family: 'SUPPORT', lineNo: '8"-P25168-61502-01', displayName: 'GUIDE PS-001', geometry: { center: { x: 0, y: 0, z: 0 } }, support: { supportType: 'GUIDE', supportTag: 'PS-001' }, pipe: { odMm: 219.075 } }, { id: 'SUP-PS-002', family: 'SUPPORT', lineNo: '8"-P25168-61502-01', displayName: 'REST PS-002', geometry: { center: { x: 6400, y: 0, z: 0 } }, support: { supportType: 'REST', supportTag: 'PS-002' }, pipe: { odMm: 219.075 } } ]; }
