import { buildSupportLoadEnrichmentConflictModel, SUPPORT_LOAD_CONFLICT_SCHEMA, SUPPORT_LOAD_CONFLICT_VERSION } from './GeometrySupportLoadConflictResolver.js?v=20260623-support-load-conflict-resolver-1';

const INSTALL_FLAG = Symbol.for('pcf-glb-support-load-conflict-bridge-v1');
let lastModel = null;
function esc(v) { return String(v ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;'); }
function workspaceState() { return globalThis.__PCF_GLB_GEOMETRY_EXPORT_WORKSPACE__?.state?.() || {}; }
function dlg() { return document.getElementById('geometry-support-load-conflict-dialog'); }
function sourceObjects() { const s = workspaceState(); if (Array.isArray(s.supportLoadHydratedObjects) && s.supportLoadHydratedObjects.length) return s.supportLoadHydratedObjects; if (Array.isArray(s.supportLoadInputModel?.hydratedObjects) && s.supportLoadInputModel.hydratedObjects.length) return s.supportLoadInputModel.hydratedObjects; if (Array.isArray(s.calculationResolvedObjects) && s.calculationResolvedObjects.length) return s.calculationResolvedObjects; if (Array.isArray(s.geometryEnrichedObjects) && s.geometryEnrichedObjects.length) return s.geometryEnrichedObjects; return Array.isArray(s.mapping?.mappedObjects) ? s.mapping.mappedObjects : []; }
function store(model) { const s = workspaceState(); if (s && typeof s === 'object') s.supportLoadConflictModel = model; return model; }
function build() { lastModel = store(buildSupportLoadEnrichmentConflictModel(sourceObjects())); render(); return lastModel; }
function summary(model) { if (!model) return '<div class="gslc-empty">Run conflict audit after LOAD → Inputs hydration.</div>'; return `<div class="gslc-summary"><div><b>${esc(model.pipeCount)}</b><span>pipe inputs</span></div><div><b>${esc(model.conflictCount)}</b><span>conflicts</span></div><div><b>${esc(model.highSeverityCount)}</b><span>high severity</span></div><div><b>${esc(model.status)}</b><span>status</span></div></div>`; }
function conflictRows(model) { const items = (Array.isArray(model?.rows) ? model.rows : []).flatMap(row => (row.fieldConflicts || []).map(conflict => ({ row, conflict }))); if (!items.length) return '<div class="gslc-empty">No support-load input conflicts detected.</div>'; return `<h4>Input Source Conflicts</h4><div class="gslc-table-wrap"><table><thead><tr><th>Line</th><th>Field</th><th>Severity</th><th>Values</th><th>Sources</th><th>Status</th></tr></thead><tbody>${items.map(({ row, conflict }) => `<tr class="${conflict.severity === 'HIGH' ? 'is-high' : 'is-medium'}"><td>${esc(row.lineNo)}</td><td>${esc(conflict.label)}<br><small>${esc(conflict.fieldPath)}</small></td><td>${esc(conflict.severity)}</td><td>${esc((conflict.values || []).join(' / '))}</td><td>${esc((conflict.sources || []).map(s => `${s.source}:${s.value}`).join(' | '))}</td><td>${esc(conflict.status)}</td></tr>`).join('')}</tbody></table></div>`; }
function pipeRows(model) { const rows = Array.isArray(model?.rows) ? model.rows : []; if (!rows.length) return ''; return `<h4>Pipe Conflict Summary</h4><div class="gslc-table-wrap"><table><thead><tr><th>Line</th><th>Status</th><th>Conflicts</th><th>High</th></tr></thead><tbody>${rows.map(row => `<tr class="${row.status === 'REVIEW_REQUIRED' ? 'is-high' : 'is-ok'}"><td>${esc(row.lineNo)}</td><td>${esc(row.status)}</td><td>${esc(row.conflictCount)}</td><td>${esc(row.highSeverityCount)}</td></tr>`).join('')}</tbody></table></div>`; }
function render() { const d = dlg(); if (!d) return; d.querySelector('[data-gslc-body]').innerHTML = `<div class="gslc-toolbar"><button type="button" data-gslc-run="true">Run Conflict Audit</button><button type="button" data-gslc-open-inputs="true">Open Inputs</button><button type="button" data-gslc-export="true">Export Conflict JSON</button><span>${esc(sourceObjects().length)} source object(s)</span></div><p class="gslc-note">Audits raw pipe attributes, XML/CII enrichment, project master hydration, deterministic derivation, and reviewed overrides. This panel does not top-up missing data and does not calculate loads.</p>${summary(lastModel)}${conflictRows(lastModel)}${pipeRows(lastModel)}`; }
function download() { if (!lastModel) build(); const blob = new Blob([JSON.stringify(lastModel, null, 2)], { type: 'application/json;charset=utf-8' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'support-load-enrichment-conflicts.json'; document.body.appendChild(a); a.click(); a.remove(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
function ensure() { let d = dlg(); if (d) return d; d = document.createElement('div'); d.id = 'geometry-support-load-conflict-dialog'; d.className = 'geometry-support-load-conflict-dialog'; d.innerHTML = `<div class="gslc-card" role="dialog"><div class="gslc-head"><div><b>Support Load Enrichment Conflict Resolver</b><small>${SUPPORT_LOAD_CONFLICT_VERSION} · ${SUPPORT_LOAD_CONFLICT_SCHEMA}</small></div><button type="button" data-gslc-close="true">x</button></div><div data-gslc-body></div></div>`; document.body.appendChild(d); d.addEventListener('click', e => { if (e.target?.closest?.('[data-gslc-close]')) { d.classList.remove('is-open'); return; } if (e.target?.closest?.('[data-gslc-run]')) { build(); return; } if (e.target?.closest?.('[data-gslc-open-inputs]')) { globalThis.__PCF_GLB_GEOMETRY_SUPPORT_LOAD_INPUTS__?.open?.(); return; } if (e.target?.closest?.('[data-gslc-export]')) download(); }, true); return d; }
function open() { const d = ensure(); d.classList.add('is-open'); if (!lastModel) build(); else render(); }
function injectToolbar(root) { const section = root?.querySelector?.('.geometry-export-workspace-tool-group'); if (!section || section.querySelector('[data-geometry-support-load-conflict-open]')) return; const b = document.createElement('button'); b.type = 'button'; b.className = 'rvm-tool-btn'; b.dataset.geometrySupportLoadConflictOpen = 'true'; b.title = 'Review support-load input conflicts before calculation'; b.innerHTML = '<span aria-hidden="true">LOAD</span><span>Conflicts</span>'; section.querySelector('.rvm-ribbon-button-row')?.appendChild(b); }
function styles() { if (document.getElementById('geometry-support-load-conflict-style')) return; const s = document.createElement('style'); s.id = 'geometry-support-load-conflict-style'; s.textContent = '.geometry-support-load-conflict-dialog{position:fixed;inset:0;display:none;align-items:flex-start;justify-content:center;padding:74px 20px;background:rgba(2,6,23,.56);z-index:12390}.geometry-support-load-conflict-dialog.is-open{display:flex}.gslc-card{width:min(1360px,calc(100vw - 44px));max-height:calc(100vh - 92px);overflow:auto;background:#0b1424;border:1px solid rgba(251,191,36,.30);border-radius:14px;padding:12px;color:#dbeafe}.gslc-toolbar,.gslc-head{display:flex;gap:8px;align-items:center;flex-wrap:wrap;justify-content:space-between}.gslc-toolbar{justify-content:flex-start}.gslc-head b,.gslc-card h4{color:#fde68a}.gslc-head small,.gslc-note,.gslc-toolbar span{color:#9fb3cc;font-size:11px}.gslc-head button,.gslc-toolbar button{border:1px solid rgba(251,191,36,.25);border-radius:8px;background:#221a09;color:#fde68a;padding:7px 10px}.gslc-summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin:8px 0}.gslc-summary div{border:1px solid rgba(251,191,36,.18);border-radius:9px;padding:8px;background:rgba(255,255,255,.04)}.gslc-summary b{display:block;font-size:18px;color:#fff}.gslc-summary span{font-size:11px;color:#9fb3cc}.gslc-table-wrap{overflow:auto;border:1px solid rgba(255,255,255,.08);border-radius:10px;margin:8px 0}.gslc-card table{border-collapse:collapse;width:100%;font-size:12px}.gslc-card th,.gslc-card td{border-bottom:1px solid rgba(255,255,255,.06);padding:6px;text-align:left;vertical-align:top}.gslc-card th{background:rgba(255,255,255,.05);color:#bfdbfe}.gslc-card tr.is-high td{background:rgba(127,29,29,.16)}.gslc-card tr.is-medium td{background:rgba(120,53,15,.14)}.gslc-card tr.is-ok td{background:rgba(20,83,45,.12)}.gslc-empty{padding:16px;color:#9fb3cc;border:1px dashed rgba(255,255,255,.14);border-radius:10px;margin:8px 0}.gslc-card small{color:#9fb3cc}'; document.head.appendChild(s); }
export function installGeometrySupportLoadConflictBridge() { if (globalThis[INSTALL_FLAG]) return globalThis.__PCF_GLB_GEOMETRY_SUPPORT_LOAD_CONFLICTS__; globalThis[INSTALL_FLAG] = true; styles(); globalThis.__PCF_GLB_GEOMETRY_SUPPORT_LOAD_CONFLICTS__ = Object.freeze({ open, build: () => build(), current: () => lastModel }); document.addEventListener('click', e => { if (e.target?.closest?.('[data-geometry-support-load-conflict-open]')) open(); }, true); const mo = new MutationObserver(records => { for (const record of records) for (const node of record.addedNodes || []) if (node?.querySelector) injectToolbar(node); }); mo.observe(document.documentElement, { childList: true, subtree: true }); injectToolbar(document); return globalThis.__PCF_GLB_GEOMETRY_SUPPORT_LOAD_CONFLICTS__; }
