import { buildGeometrySupportLoadInputModel, SUPPORT_LOAD_INPUT_MODULE_ID, PIPE_SUPPORT_LOAD_INPUT_SCHEMA } from './GeometrySupportLoadInputModel.js?v=20260622-pipe-support-load-input-hydrator-1';

export const GEOMETRY_CALCULATION_CANVAS_SCHEMA = 'geometry-calculation-canvas/v1';
export const GEOMETRY_CALCULATION_CANVAS_VERSION = '20260622-pipe-support-load-input-hydrator-1';
const SUPPORT_LOAD_MODULE_ID = 'support-load-readiness/v1';
const MAX_CALC_OBJECTS = 80000;
const SUPPORT_LOAD_REQUIRED_FIELDS = Object.freeze(['family','support.supportType','geometry.center','pipe.odMm','pipe.wallThicknessMm','pipe.material','process.fluidDensityKgM3']);
const SUPPORT_LOAD_OPTIONAL_FIELDS = Object.freeze(['support.supportTag','support.gapMm','geometry.lengthMm','geometry.axis','lineNo','pipe.schedule','process.pressureBar','process.temperatureC','pipe.insulationThicknessMm','pipe.insulationDensityKgM3']);
const PIPE_SUPPORT_LOAD_INPUT_REQUIRED_FIELDS = Object.freeze(['attributes.supportLoadInput.identity.nps','attributes.supportLoadInput.identity.pipeOdMm','attributes.supportLoadInput.pipePhysical.wallThicknessMm','attributes.supportLoadInput.pipePhysical.unitPipeWtKgPerM','attributes.supportLoadInput.process.tempExpC1','attributes.supportLoadInput.process.fluidWtOpeKgPerM','attributes.supportLoadInput.process.fluidWtHydKgPerM','attributes.supportLoadInput.spans.autoSpanMm or attributes.supportLoadInput.spans.depSpanMm']);
export const GEOMETRY_CALCULATION_MODULES = Object.freeze([Object.freeze({moduleId:SUPPORT_LOAD_MODULE_ID,displayName:'Support Load Readiness',schemaVersion:GEOMETRY_CALCULATION_CANVAS_SCHEMA,requiredFields:SUPPORT_LOAD_REQUIRED_FIELDS,optionalFields:SUPPORT_LOAD_OPTIONAL_FIELDS,description:'Validates confirmed mapped support objects before support-load formulas are allowed to run.'}),Object.freeze({moduleId:SUPPORT_LOAD_INPUT_MODULE_ID,displayName:'Pipe-Level Support Load Input Hydrator',schemaVersion:'geometry-support-load-input-model/v1',pipeInputSchema:PIPE_SUPPORT_LOAD_INPUT_SCHEMA,requiredFields:PIPE_SUPPORT_LOAD_INPUT_REQUIRED_FIELDS,optionalFields:Object.freeze(['attributes.supportLoadInput.supportRefs','attributes.supportLoadInput.spans.autoSpanBySupport']),description:'Writes audited formula inputs onto pipe.attributes.supportLoadInput and keeps support rows as references without calculating loads.'})]);
export function valueAtPath(input,path){if(!input||!path)return undefined;const parts=String(path).split('.');let current=input;for(const part of parts){if(part.includes(' or '))return part.split(/\s+or\s+/).some(x=>valueAtPath(current,x)!==undefined)?true:undefined;if(current===undefined||current===null)return undefined;current=current[part];}return current;}
function hasValue(input,path){if(String(path).includes(' or '))return String(path).split(/\s+or\s+/).some(x=>hasValue(input,x));const v=valueAtPath(input,path);if(v===undefined||v===null)return false;if(typeof v==='string')return v.trim()!=='';if(typeof v==='number')return Number.isFinite(v);if(Array.isArray(v))return v.length>0;if(typeof v==='object')return Object.keys(v).length>0;return true;}
function normalizeMappedObjects(mappedObjects){return (Array.isArray(mappedObjects)?mappedObjects:[]).slice(0,MAX_CALC_OBJECTS).filter(Boolean);}
function isRejected(object){return String(object?.mappingStatus||'').toUpperCase()==='REJECTED';}
function supportRows(mappedObjects){return normalizeMappedObjects(mappedObjects).filter(o=>o.family==='SUPPORT'&&!isRejected(o));}
function readinessForObject(object,module=GEOMETRY_CALCULATION_MODULES[0]){const missingFields=[],presentFields=[];for(const field of module.requiredFields||[]){if(field==='family'){if(object.family==='SUPPORT')presentFields.push(field);else missingFields.push(field);continue;}if(hasValue(object,field))presentFields.push(field);else missingFields.push(field);}const optionalPresent=(module.optionalFields||[]).filter(field=>hasValue(object,field));const status=missingFields.length?'BLOCKED':'READY';return Object.freeze({objectId:object.sourceId||object.id,displayName:object.displayName||object.id,family:object.family||'UNKNOWN',supportType:object.support?.supportType||'',supportTag:object.support?.supportTag||'',mappingStatus:object.mappingStatus||'UNKNOWN',mappingConfidence:object.mappingConfidence||0,status,presentFields,missingFields,optionalPresent,warnings:missingFields.length?[`Missing required calculation field(s): ${missingFields.join(', ')}`]:[]});}
export function evaluateSupportLoadReadiness(mappedObjects,options={}){const module=GEOMETRY_CALCULATION_MODULES.find(item=>item.moduleId===SUPPORT_LOAD_MODULE_ID);const rows=supportRows(mappedObjects).map(object=>readinessForObject(object,module));const readyCount=rows.filter(r=>r.status==='READY').length;const blockedCount=rows.length-readyCount;const rejectedCount=normalizeMappedObjects(mappedObjects).filter(isRejected).length;return Object.freeze({schemaVersion:GEOMETRY_CALCULATION_CANVAS_SCHEMA,version:GEOMETRY_CALCULATION_CANVAS_VERSION,moduleId:SUPPORT_LOAD_MODULE_ID,displayName:module.displayName,evaluatedAt:options.evaluatedAt||new Date().toISOString(),objectCount:rows.length,readyCount,blockedCount,rejectedCount,status:rows.length===0?'EMPTY':blockedCount?'BLOCKED':'READY',requiredFields:module.requiredFields,optionalFields:module.optionalFields,rows,assumptions:Object.freeze(['This legacy readiness phase validates mapped support objects only; it does not calculate support loads.','The pipe-level support-load input hydrator is the source of truth for future support-load calculation inputs.','Missing schedule, material, process, or weight data blocks the support-load module.'])});}
export function evaluateGeometryCalculationModules(mappedObjects,options={}){const supportLoad=evaluateSupportLoadReadiness(mappedObjects,options);const supportLoadInputModel=buildGeometrySupportLoadInputModel(mappedObjects,options);return Object.freeze({schemaVersion:GEOMETRY_CALCULATION_CANVAS_SCHEMA,version:GEOMETRY_CALCULATION_CANVAS_VERSION,evaluatedAt:supportLoad.evaluatedAt,moduleCount:GEOMETRY_CALCULATION_MODULES.length,modules:GEOMETRY_CALCULATION_MODULES,results:Object.freeze([supportLoad,supportLoadInputModel]),summary:Object.freeze({readyModules:[supportLoad.status,supportLoadInputModel.status].filter(s=>s==='READY'||s==='INPUT_READY').length,blockedModules:[supportLoad.status,supportLoadInputModel.status].filter(s=>s==='BLOCKED').length,emptyModules:[supportLoad.status,supportLoadInputModel.status].filter(s=>s==='EMPTY').length,supportCandidates:supportLoad.objectCount,supportReady:supportLoad.readyCount,supportBlocked:supportLoad.blockedCount,supportLoadInputReady:supportLoadInputModel.readyCount,supportLoadInputBlocked:supportLoadInputModel.blockedCount,pipeInputReady:supportLoadInputModel.pipeInputReadyCount,pipeInputPartial:supportLoadInputModel.pipeInputPartialCount,pipeInputBlocked:supportLoadInputModel.pipeInputBlockedCount}),supportLoadInputModel,hydratedObjects:supportLoadInputModel.hydratedObjects});}
export function findGeometryCalculationModule(moduleId){return GEOMETRY_CALCULATION_MODULES.find(module=>module.moduleId===moduleId)||null;}
