import { calculateSupportLoadResultsFromInputModel, SUPPORT_LOAD_FORMULA_INFO_TEXT, SUPPORT_LOAD_FORMULA_SCHEMA, SUPPORT_LOAD_FORMULA_VERSION } from './GeometrySupportLoadFormulaEngine.js?v=20260622-support-load-result-writeback-audit-1';
const INSTALL_FLAG = Symbol.for('pcf-glb-geometry-support-load-formula-bridge-v2');
let lastResults = null;
function esc(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function cell(v){return v===undefined||v===null||v===''?'':esc(v);}
function workspaceApi(){return globalThis.__PCF_GLB_GEOMETRY_EXPORT_WORKSPACE__||null;}
function workspaceState(){return workspaceApi()?.state?.()||{};}
function inputModel(){return workspaceState().supportLoadInputModel||null;}
function dialog(){return document.getElementById('geometry-support-load-formula-dialog');}
function store(results){const s=workspaceState();if(s&&typeof s==='object'){s.supportLoadFormulaResults=results;s.supportLoadCalculatedObjects=Array.isArray(results?.calculatedObjects)?results.calculatedObjects:[];}return results;}
function runFormulas(){const model=inputModel();lastResults=store(calculateSupportLoadResultsFromInputModel(model));render();return lastResults;}
function summary(r){if(!r)return '<div class="gslf-empty">Run LOAD → Inputs, review/lock the ready pipe inputs, then run formulas.</div>';return `<div class="gslf-summary"><div><b>${esc(r.pipeInputCount)}</b><span>pipe inputs</span></div><div><b>${esc(r.calculatedPipeCount)}</b><span>calculated</span></div><div><b>${esc(r.blockedPipeCount)}</b><span>blocked</span></div><div><b>${esc(r.supportResultCount)}</b><span>support refs</span></div><div><b>${esc(r.status)}</b><span>status</span></div></div>`;}
function formulaInfo(){return `<div class="gslf-info-row"><span class="gslf-info-icon" title="${esc(SUPPORT_LOAD_FORMULA_INFO_TEXT)}" aria-label="Formula information">i</span><details><summary>Formula details</summary><pre>${esc(SUPPORT_LOAD_FORMULA_INFO_TEXT)}</pre></details></div>`;}
function writebackInfo(r){const a=r?.writebackAudit;if(!a)return '';return `<div class="gslf-writeback"><b>Writeback:</b> ${esc(a.status)} · pipe writes ${esc(a.pipeCalculatedWriteCount)} · support writes ${esc(a.supportCalculatedWriteCount)} · stale cleared ${esc((a.stalePipeResultClearedCount||0)+(a.staleSupportReferenceClearedCount||0))} · input mutations ${esc(a.inputPackageMutatedCount)}</div>`;}
function pipeRows(r){const rows=Array.isArray(r?.pipeResults)?r.pipeResults.slice(0,180):[];if(!rows.length)return '<div class="gslf-empty">No calculated pipe rows.</div>';return `<h4>Pipe Calculated Fields</h4><div class="gslf-table-wrap"><table><thead><tr><th>Line</th><th>Status</th><th>OPE_V_A</th><th>HYD_V_A</th><th>OPE_V_DEP</th><th>HYD_V_DEP</th><th>Rounded Guide A</th><th>Guide A</th><th>Rounded Guide DEP</th><th>Guide DEP</th><th>LineStop H</th><th>Reason / Missing</th></tr></thead><tbody>${rows.map(row=>{const c=row.calculatedFields||{},v=c.vertical||{},g=c.guide||{},ls=c.lineStop||{};return `<tr class="${row.status==='CALCULATED'?'is-calculated':'is-blocked'}"><td>${esc(row.lineNo||row.sourceObjectId||row.inputKey)}</td><td>${esc(row.status)}</td><td>${cell(v.opeVA)}</td><td>${cell(v.hydVA)}</td><td>${cell(v.opeVDep)}</td><td>${cell(v.hydVDep)}</td><td>${cell(g.roundedGuideHA)}</td><td>${cell(g.guideHA)}</td><td>${cell(g.roundedGuideHDep)}</td><td>${cell(g.guideHDep)}</td><td>${cell(ls.lineStopH)}</td><td>${esc(row.reason||((row.missing||[]).join(', ')))}</td></tr>`;}).join('')}</tbody></table></div>`;}
function supportRows(r){const rows=Array.isArray(r?.supportRows)?r.supportRows.slice(0,180):[];if(!rows.length)return '<div class="gslf-empty">No support references were available from locked pipe inputs.</div>';return `<h4>Support Reference Results</h4><div class="gslf-table-wrap"><table><thead><tr><th>Support</th><th>Type</th><th>Pipe</th><th>OPE_V_A</th><th>OPE_V_DEP</th><th>Guide A</th><th>Guide DEP</th><th>LineStop H</th><th>Applies</th></tr></thead><tbody>${rows.map(row=>{const v=row.vertical||{},g=row.guide||{},ls=row.lineStop||{},a=row.applies||{};return `<tr class="${row.status==='CALCULATED'?'is-calculated':'is-blocked'}"><td>${esc(row.supportTag||row.supportId)}</td><td>${esc(row.supportType)}</td><td>${esc(row.associatedPipeId)}</td><td>${cell(v.opeVA)}</td><td>${cell(v.opeVDep)}</td><td>${cell(g.guideHA)}</td><td>${cell(g.guideHDep)}</td><td>${cell(ls.lineStopH)}</td><td>${esc(Object.entries(a).filter(([,ok])=>ok).map(([k])=>k).join(', '))}</td></tr>`;}).join('')}</tbody></table></div>`;}
function render(){const d=dialog();if(!d)return;const model=inputModel();const locked=model?.calcReadyPipeInputCount||0;d.querySelector('[data-gslf-body]').innerHTML=`<div class="gslf-toolbar"><button type="button" data-gslf-run="true">Run Locked Formulas</button><button type="button" data-gslf-open-inputs="true">Open LOAD Inputs</button><button type="button" data-gslf-export="true">Export Formula Results JSON</button><span>${esc(model?.pipeInputCount||0)} pipe input(s) · ${esc(locked)} calc-gated</span></div><p class="gslf-note">This engine reads only locked <code>pipe.attributes.supportLoadInput</code> packages and writes calculated outputs separately as <code>calculatedFields.supportLoads</code>. It does not hydrate, enrich, associate, or fabricate missing inputs.</p>${formulaInfo()}${summary(lastResults)}${writebackInfo(lastResults)}${pipeRows(lastResults)}${supportRows(lastResults)}`;}
function open(){const d=ensure();d.classList.add('is-open');render();}
function download(){if(!lastResults)runFormulas();if(!lastResults)return;const blob=new Blob([JSON.stringify(lastResults,null,2)],{type:'application/json;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='geometry-support-load-formula-results.json';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function ensure(){let d=dialog();if(d)return d;d=document.createElement('div');d.id='geometry-support-load-formula-dialog';d.className='geometry-support-load-formula-dialog';d.innerHTML=`<div class="gslf-card" role="dialog"><div class="gslf-head"><div><b>Support Load Formula Engine</b><small>${SUPPORT_LOAD_FORMULA_VERSION} · ${SUPPORT_LOAD_FORMULA_SCHEMA}</small></div><button type="button" data-gslf-close="true">x</button></div><div data-gslf-body></div></div>`;document.body.appendChild(d);d.addEventListener('click',e=>{if(e.target?.closest?.('[data-gslf-close]')){d.classList.remove('is-open');return;}if(e.target?.closest?.('[data-gslf-run]')){runFormulas();return;}if(e.target?.closest?.('[data-gslf-open-inputs]')){globalThis.__PCF_GLB_GEOMETRY_SUPPORT_LOAD_INPUTS__?.open?.();return;}if(e.target?.closest?.('[data-gslf-export]'))download();},true);return d;}
function injectToolbar(root){const section=root?.querySelector?.('.geometry-export-workspace-tool-group');if(!section||section.querySelector('[data-geometry-support-load-formula-open]'))return;const b=document.createElement('button');b.type='button';b.className='rvm-tool-btn';b.dataset.geometrySupportLoadFormulaOpen='true';b.title='Run locked Access support-load formulas';b.innerHTML='<span aria-hidden="true">LOAD</span><span>Calc</span>';section.querySelector('.rvm-ribbon-button-row')?.appendChild(b);}
function styles(){if(document.getElementById('geometry-support-load-formula-style'))return;const s=document.createElement('style');s.id='geometry-support-load-formula-style';s.textContent='.geometry-support-load-formula-dialog{position:fixed;inset:0;display:none;align-items:flex-start;justify-content:center;padding:74px 20px;background:rgba(2,6,23,.56);z-index:12390}.geometry-support-load-formula-dialog.is-open{display:flex}.gslf-card{width:min(1380px,calc(100vw - 44px));max-height:calc(100vh - 92px);overflow:auto;background:#0b1424;border:1px solid rgba(126,190,255,.30);border-radius:14px;padding:12px;color:#dbeafe}.gslf-head,.gslf-toolbar,.gslf-info-row{display:flex;gap:8px;align-items:center;justify-content:space-between;flex-wrap:wrap}.gslf-toolbar,.gslf-info-row{justify-content:flex-start}.gslf-head b,.gslf-card h4{color:#bfdbfe}.gslf-head small,.gslf-toolbar span,.gslf-note,.gslf-info-row summary{color:#9fb3cc;font-size:11px}.gslf-head button,.gslf-toolbar button{border:1px solid rgba(126,190,255,.24);border-radius:8px;background:#132238;color:#dbeafe;padding:7px 10px}.gslf-info-icon{display:inline-grid;place-items:center;width:20px;height:20px;border-radius:999px;border:1px solid rgba(126,190,255,.35);color:#bfdbfe;font-weight:700}.gslf-writeback{margin:8px 0;padding:8px 10px;border:1px solid rgba(126,190,255,.16);border-radius:10px;background:rgba(59,130,246,.06);color:#c7d2fe;font-size:11px}.gslf-info-row pre{white-space:pre-wrap;background:#08111f;border:1px solid rgba(126,190,255,.16);border-radius:10px;padding:10px;max-width:100%;overflow:auto;color:#dbeafe}.gslf-summary{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:8px;margin:8px 0}.gslf-summary div{border:1px solid rgba(126,190,255,.15);border-radius:9px;padding:8px;background:rgba(255,255,255,.035)}.gslf-table-wrap{overflow:auto;max-height:520px}.gslf-table-wrap table{border-collapse:collapse;min-width:100%;font-size:11px}.gslf-table-wrap th,.gslf-table-wrap td{border:1px solid rgba(126,190,255,.13);padding:5px 7px;text-align:left;white-space:nowrap}.gslf-table-wrap th{position:sticky;top:0;background:#132238;color:#bfdbfe}.gslf-table-wrap tr.is-calculated td{background:rgba(34,197,94,.06)}.gslf-table-wrap tr.is-blocked td{background:rgba(239,68,68,.06)}.gslf-empty{padding:16px;border:1px dashed rgba(148,163,184,.22);border-radius:10px;color:#9fb3cc;text-align:center}';document.head.appendChild(s);}
function attach(){const root=document.querySelector('[data-rvm-viewer]');if(!root)return false;injectToolbar(root);return true;}
function click(e){if(!e.target?.closest?.('[data-geometry-support-load-formula-open]'))return;e.preventDefault();e.stopPropagation();open();}
export function installGeometrySupportLoadFormulaBridge(){if(typeof document==='undefined')return;if(globalThis[INSTALL_FLAG])return;globalThis[INSTALL_FLAG]=true;styles();document.addEventListener('click',click,true);let attempts=0;const wait=()=>{attempts+=1;if(!attach()&&attempts<180)setTimeout(wait,300);};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wait,{once:true});else wait();globalThis.addEventListener?.('rvm-model-loaded',()=>setTimeout(wait,320));globalThis.__PCF_GLB_GEOMETRY_SUPPORT_LOAD_FORMULAS__={version:SUPPORT_LOAD_FORMULA_VERSION,schema:SUPPORT_LOAD_FORMULA_SCHEMA,open,run:runFormulas,lastResults:()=>lastResults,formulaInfo:SUPPORT_LOAD_FORMULA_INFO_TEXT};}
