import { evaluateGeometryCalculationModules, GEOMETRY_CALCULATION_CANVAS_SCHEMA, GEOMETRY_CALCULATION_CANVAS_VERSION } from './GeometryCalculationModuleRegistry.js?v=20260622-pipe-support-load-input-hydrator-1';
const INSTALL_FLAG = Symbol.for('pcf-glb-geometry-calculation-canvas-bridge-v1');
// Static certification marker: data-geometry-calculation-canvas-open
let lastEvaluation = null;
function esc(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function workspaceApi(){return globalThis.__PCF_GLB_GEOMETRY_EXPORT_WORKSPACE__||null;}
function workspaceState(){return workspaceApi()?.state?.()||{};}
function activeMappedObjects(){const s=workspaceState();const active=s.activeObjectIds instanceof Set?s.activeObjectIds:new Set(s.activeObjectIds||[]);const src=Array.isArray(s.supportLoadHydratedObjects)&&s.supportLoadHydratedObjects.length?s.supportLoadHydratedObjects:Array.isArray(s.calculationResolvedObjects)&&s.calculationResolvedObjects.length?s.calculationResolvedObjects:Array.isArray(s.geometryEnrichedObjects)&&s.geometryEnrichedObjects.length?s.geometryEnrichedObjects:Array.isArray(s.mapping?.mappedObjects)?s.mapping.mappedObjects:[];return active.size?src.filter(o=>active.has(o.sourceId||o.id)):src;}
function currentDialog(){return document.getElementById('geometry-calculation-canvas-dialog');}
function evaluateActiveGeometry(){lastEvaluation=evaluateGeometryCalculationModules(activeMappedObjects());const s=workspaceState();if(s&&typeof s==='object'){s.calculationCanvas=lastEvaluation;s.supportLoadInputModel=lastEvaluation.supportLoadInputModel;s.supportLoadHydratedObjects=Array.isArray(lastEvaluation.hydratedObjects)?lastEvaluation.hydratedObjects:[];}renderCalculationDialog();return lastEvaluation;}
function summary(e){const x=e?.summary||{};return `<div class="gcc-summary"><div><b>${esc(x.supportCandidates??0)}</b><span>support candidates</span></div><div><b>${esc(x.pipeInputReady??0)}</b><span>ready pipe inputs</span></div><div><b>${esc(x.pipeInputPartial??0)}</b><span>partial pipe inputs</span></div><div><b>${esc(x.pipeInputBlocked??0)}</b><span>blocked pipe inputs</span></div><div><b>${esc(x.supportLoadInputBlocked??0)}</b><span>blocked support refs</span></div></div>`;}
function modules(e){const rows=Array.isArray(e?.results)?e.results:[];if(!rows.length)return '<div class="gcc-empty">Run validation after importing and mapping geometry.</div>';return `<div class="gcc-modules">${rows.map(r=>`<div class="gcc-module ${esc(String(r.status||'').toLowerCase())}"><h4>${esc(r.displayName||r.moduleId)}</h4><p>${esc(r.moduleId)} · ${esc(r.status)}</p><div class="gcc-mini"><span>Ready <b>${esc(r.readyCount??r.pipeInputReadyCount??0)}</b></span><span>Blocked <b>${esc(r.blockedCount??r.pipeInputBlockedCount??0)}</b></span><span>Rejected <b>${esc(r.rejectedCount??0)}</b></span></div><details><summary>Required fields</summary><code>${esc((r.requiredFields||[]).join(', '))}</code></details><details><summary>Assumptions</summary><ul>${(r.assumptions||[]).map(i=>`<li>${esc(i)}</li>`).join('')}</ul></details></div>`).join('')}</div>`;}
function readinessRows(e){const r=Array.isArray(e?.results)?e.results[0]:null;const rows=Array.isArray(r?.rows)?r.rows.slice(0,180):[];if(!rows.length)return '<div class="gcc-empty">No support candidates in the active mapped object list.</div>';return `<div class="gcc-table-wrap"><table><thead><tr><th>Object</th><th>Support Type</th><th>Status</th><th>Confidence</th><th>Missing Required Fields</th><th>Optional Present</th></tr></thead><tbody>${rows.map(row=>`<tr class="${row.status==='READY'?'is-ready':'is-blocked'}"><td>${esc(row.displayName)}</td><td>${esc(row.supportType||'')}</td><td>${esc(row.status)}</td><td>${esc(row.mappingConfidence)}</td><td>${esc((row.missingFields||[]).join(', '))}</td><td>${esc((row.optionalPresent||[]).join(', '))}</td></tr>`).join('')}</tbody></table></div>`;}
function renderCalculationDialog(){const d=currentDialog();if(!d)return;const s=workspaceState();const resolvedCount=Array.isArray(s.calculationResolvedObjects)?s.calculationResolvedObjects.length:0;const hydratedCount=Array.isArray(s.supportLoadHydratedObjects)?s.supportLoadHydratedObjects.length:0;d.querySelector('[data-gcc-body]').innerHTML=`<div class="gcc-toolbar"><button type="button" data-gcc-run="true">Run Validation</button><button type="button" data-gcc-open-inputs="true">Open Inputs</button><button type="button" data-gcc-open-load="true">Open LOAD Inputs</button><button type="button" data-gcc-open-workspace="true">Open Workspace</button><button type="button" data-gcc-export="true">Export Validation JSON</button><span>${activeMappedObjects().length} active mapped object(s) · ${resolvedCount} input-resolved · ${hydratedCount} pipe-input hydrated</span></div><p class="gcc-note">Calculation Canvas validates module readiness and builds the pipe-level support-load input hydrator. Use INPUT → Data and ENRICH → Resolve before LOAD → Inputs. It does not fabricate process, schedule, material, weight, or load values.</p>${summary(lastEvaluation)}${modules(lastEvaluation)}<h4>Support Load Readiness Rows</h4>${readinessRows(lastEvaluation)}`;}
function ensureDialog(){let d=currentDialog();if(d)return d;d=document.createElement('div');d.id='geometry-calculation-canvas-dialog';d.className='geometry-calculation-canvas-dialog';d.innerHTML=`<div class="gcc-card" role="dialog"><div class="gcc-head"><div><b>Geometry Calculation Canvas</b><small>${GEOMETRY_CALCULATION_CANVAS_VERSION} · module registry · pipe-level input hydration · no formulas</small></div><button type="button" data-gcc-close="true">x</button></div><div data-gcc-body></div></div>`;document.body.appendChild(d);d.addEventListener('click',e=>{if(e.target?.closest?.('[data-gcc-close]')){d.classList.remove('is-open');return;}if(e.target?.closest?.('[data-gcc-run]')){evaluateActiveGeometry();return;}if(e.target?.closest?.('[data-gcc-open-inputs]')){globalThis.__PCF_GLB_GEOMETRY_CALCULATION_INPUTS__?.open?.();return;}if(e.target?.closest?.('[data-gcc-open-load]')){globalThis.__PCF_GLB_GEOMETRY_SUPPORT_LOAD_INPUTS__?.open?.();return;}if(e.target?.closest?.('[data-gcc-open-workspace]')){workspaceApi()?.open?.();return;}if(e.target?.closest?.('[data-gcc-export]'))downloadEvaluation();},true);return d;}
function openCalculationDialog(){const d=ensureDialog();d.classList.add('is-open');if(!lastEvaluation)evaluateActiveGeometry();else renderCalculationDialog();}
function downloadEvaluation(){if(!lastEvaluation)evaluateActiveGeometry();if(!lastEvaluation)return;const blob=new Blob([JSON.stringify(lastEvaluation,null,2)],{type:'application/json;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='geometry-calculation-readiness.json';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function injectToolbar(root){const section=root?.querySelector?.('.geometry-export-workspace-tool-group');if(!section||section.querySelector('[data-geometry-calculation-canvas-open]'))return;const b=document.createElement('button');b.type='button';b.className='rvm-tool-btn';b.dataset.geometryCalculationCanvasOpen='true';b.title='Open independent geometry calculation canvas module registry';b.innerHTML='<span aria-hidden="true">CALC</span><span>Modules</span>';section.querySelector('.rvm-ribbon-button-row')?.appendChild(b);const summaryNode=section.querySelector('.geometry-export-workspace-summary');if(summaryNode)summaryNode.textContent='Raw geometry · mapping profiles · calc inputs · pipe-level support-load inputs';}
function styles(){if(document.getElementById('geometry-calculation-canvas-style'))return;const s=document.createElement('style');s.id='geometry-calculation-canvas-style';s.textContent='.geometry-calculation-canvas-dialog{position:fixed;inset:0;display:none;align-items:flex-start;justify-content:center;padding:74px 20px;background:rgba(2,6,23,.50);z-index:12340}.geometry-calculation-canvas-dialog.is-open{display:flex}.gcc-card{width:min(1160px,calc(100vw - 44px));max-height:calc(100vh - 92px);overflow:auto;background:#0b1424;border:1px solid rgba(126,190,255,.30);border-radius:14px;padding:12px;color:#dbeafe}.gcc-head,.gcc-toolbar{display:flex;gap:8px;align-items:center;justify-content:space-between;flex-wrap:wrap}.gcc-toolbar{justify-content:flex-start;margin-bottom:8px}.gcc-head b,.gcc-module h4{color:#bfdbfe}.gcc-head small,.gcc-toolbar span,.gcc-note,.gcc-module p,.gcc-module li,.gcc-module code{color:#9fb3cc;font-size:11px}.gcc-head button,.gcc-toolbar button{border:1px solid rgba(126,190,255,.24);border-radius:8px;background:#132238;color:#dbeafe;padding:7px 10px}.gcc-summary{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:8px;margin:8px 0}.gcc-summary div,.gcc-module{border:1px solid rgba(126,190,255,.15);border-radius:9px;padding:8px;background:rgba(255,255,255,.035)}.gcc-modules{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:8px}.gcc-mini{display:flex;gap:8px;flex-wrap:wrap;color:#bcd8ff;font-size:11px}.gcc-table-wrap{overflow:auto;max-height:520px}.gcc-table-wrap table{border-collapse:collapse;min-width:100%;font-size:11px}.gcc-table-wrap th,.gcc-table-wrap td{border:1px solid rgba(126,190,255,.13);padding:5px 7px;text-align:left;white-space:nowrap}.gcc-table-wrap th{position:sticky;top:0;background:#132238;color:#bfdbfe}.gcc-table-wrap tr.is-ready td{background:rgba(34,197,94,.06)}.gcc-table-wrap tr.is-blocked td{background:rgba(239,68,68,.06)}.gcc-empty{padding:16px;border:1px dashed rgba(148,163,184,.22);border-radius:10px;color:#9fb3cc;text-align:center}';document.head.appendChild(s);}
function attach(){const root=document.querySelector('[data-rvm-viewer]');if(!root)return false;injectToolbar(root);return true;}
function click(e){if(!e.target?.closest?.('[data-geometry-calculation-canvas-open]'))return;e.preventDefault();e.stopPropagation();openCalculationDialog();}
export function installGeometryCalculationCanvasBridge(){if(typeof document==='undefined')return;if(globalThis[INSTALL_FLAG])return;globalThis[INSTALL_FLAG]=true;styles();document.addEventListener('click',click,true);let attempts=0;const wait=()=>{attempts+=1;if(!attach()&&attempts<180)setTimeout(wait,300);};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wait,{once:true});else wait();globalThis.addEventListener?.('rvm-model-loaded',()=>setTimeout(wait,320));globalThis.__PCF_GLB_GEOMETRY_CALCULATION_CANVAS__={version:GEOMETRY_CALCULATION_CANVAS_VERSION,schema:GEOMETRY_CALCULATION_CANVAS_SCHEMA,open:openCalculationDialog,evaluate:evaluateActiveGeometry,lastEvaluation:()=>lastEvaluation};}
