import { buildDefaultSupportLoadMasterData, normalizeSupportLoadMasterDataPackage, summarizeSupportLoadMasterData, SUPPORT_LOAD_MASTER_DATA_SCHEMA, SUPPORT_LOAD_MASTER_DATA_VERSION } from './GeometrySupportLoadMasterData.js?v=20260623-support-load-master-data-1';

const INSTALL_FLAG = Symbol.for('pcf-glb-geometry-support-load-master-data-bridge-v1');
let lastMasterData = null;

function esc(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function cell(v){return v===undefined||v===null||v===''?'':esc(v);}
function workspaceApi(){return globalThis.__PCF_GLB_GEOMETRY_EXPORT_WORKSPACE__||null;}
function workspaceState(){return workspaceApi()?.state?.()||{};}
function dialog(){return document.getElementById('geometry-support-load-master-data-dialog');}
function stateMasterData(){return workspaceState().supportLoadMasterData||null;}
function store(data){const s=workspaceState();lastMasterData=normalizeSupportLoadMasterDataPackage(data||buildDefaultSupportLoadMasterData());if(s&&typeof s==='object')s.supportLoadMasterData=lastMasterData;return lastMasterData;}
function current(){return store(stateMasterData()||lastMasterData||buildDefaultSupportLoadMasterData());}
function summary(data){const s=summarizeSupportLoadMasterData(data);return `<div class="gslm-summary"><div><b>${esc(s.depSpanRowCount)}</b><span>DEP spans</span></div><div><b>${esc(s.materialDensityRowCount)}</b><span>material density</span></div><div><b>${esc(s.pipeWeightRowCount)}</b><span>pipe weight</span></div><div><b>${esc(s.hydroDensityProfileCount)}</b><span>hydro profiles</span></div><div><b>${esc(s.tempFunctionProfileCount)}</b><span>TempfnC</span></div><div><b>${esc(s.roundingProfileCount)}</b><span>rounding</span></div><div><b>${esc(s.status)}</b><span>status</span></div></div>`;}
function rows(title, rows, columns){const list=Array.isArray(rows)?rows.slice(0,120):[];if(!list.length)return `<h4>${esc(title)}</h4><div class="gslm-empty">No rows.</div>`;return `<h4>${esc(title)}</h4><div class="gslm-table-wrap"><table><thead><tr>${columns.map(c=>`<th>${esc(c.label)}</th>`).join('')}</tr></thead><tbody>${list.map(row=>`<tr>${columns.map(c=>`<td>${cell(row[c.key])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function render(){const d=dialog();if(!d)return;const data=current();d.querySelector('[data-gslm-body]').innerHTML=`<div class="gslm-toolbar"><button type="button" data-gslm-reset="true">Load Defaults</button><button type="button" data-gslm-apply="true">Apply JSON</button><button type="button" data-gslm-export="true">Export Master JSON</button><button type="button" data-gslm-open-inputs="true">Open LOAD Inputs</button><span>${esc(SUPPORT_LOAD_MASTER_DATA_VERSION)} · ${esc(SUPPORT_LOAD_MASTER_DATA_SCHEMA)}</span></div><p class="gslm-note">Project master data is a controlled source for future input hydration. It does not run formulas, does not mutate calculated fields, and does not silently top-up missing pipe inputs. Rehydrate and relock inputs explicitly after changing master data.</p>${summary(data)}<details open><summary>Master Data JSON</summary><textarea data-gslm-json spellcheck="false">${esc(JSON.stringify(data,null,2))}</textarea></details>${rows('DEP Span Table',data.depSpanRows,[{key:'nps',label:'NPS'},{key:'pipeOdMm',label:'Pipe OD mm'},{key:'depSpanMm',label:'DEPSpan mm'},{key:'source',label:'Source'}])}${rows('Material Density Table',data.materialDensityRows,[{key:'materialCategory',label:'Category'},{key:'materialCode',label:'Code'},{key:'materialName',label:'Name'},{key:'materialDensityKgM3',label:'Density kg/m3'},{key:'source',label:'Source'}])}${rows('Pipe Weight Table',data.pipeWeightRows,[{key:'nps',label:'NPS'},{key:'pipeOdMm',label:'OD'},{key:'schedule',label:'Schedule'},{key:'wallThicknessMm',label:'Wall mm'},{key:'unitPipeWtKgPerM',label:'kg/m'},{key:'source',label:'Source'}])}${rows('Hydro Density Profiles',data.hydroDensityProfiles,[{key:'profileId',label:'Profile'},{key:'fluidDensityHydKgM3',label:'Density kg/m3'},{key:'description',label:'Description'},{key:'source',label:'Source'}])}${rows('Temperature Function Profiles',data.tempFunctionProfiles,[{key:'profileId',label:'Profile'},{key:'mode',label:'Mode'},{key:'source',label:'Source'}])}${rows('Rounding Profiles',data.roundingProfiles,[{key:'profileId',label:'Profile'},{key:'roundMajor',label:'Major'},{key:'roundStep',label:'Step'},{key:'roundMode',label:'Mode'},{key:'source',label:'Source'}])}`;}
function applyJson(){const d=dialog();const raw=d?.querySelector('[data-gslm-json]')?.value||'{}';let parsed={};try{parsed=JSON.parse(raw);}catch(error){alert(`Invalid support-load master JSON: ${error.message}`);return;}store(parsed);render();}
function reset(){store(buildDefaultSupportLoadMasterData());render();}
function download(){const data=current();const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='geometry-support-load-master-data.json';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function open(){const d=ensure();d.classList.add('is-open');render();}
function ensure(){let d=dialog();if(d)return d;d=document.createElement('div');d.id='geometry-support-load-master-data-dialog';d.className='geometry-support-load-master-data-dialog';d.innerHTML=`<div class="gslm-card" role="dialog"><div class="gslm-head"><div><b>Support Load Master Data Manager</b><small>${SUPPORT_LOAD_MASTER_DATA_VERSION} · ${SUPPORT_LOAD_MASTER_DATA_SCHEMA}</small></div><button type="button" data-gslm-close="true">x</button></div><div data-gslm-body></div></div>`;document.body.appendChild(d);d.addEventListener('click',e=>{if(e.target?.closest?.('[data-gslm-close]')){d.classList.remove('is-open');return;}if(e.target?.closest?.('[data-gslm-reset]')){reset();return;}if(e.target?.closest?.('[data-gslm-apply]')){applyJson();return;}if(e.target?.closest?.('[data-gslm-export]')){download();return;}if(e.target?.closest?.('[data-gslm-open-inputs]')){globalThis.__PCF_GLB_GEOMETRY_SUPPORT_LOAD_INPUTS__?.open?.();return;}},true);return d;}
function injectToolbar(root){const section=root?.querySelector?.('.geometry-export-workspace-tool-group');if(!section||section.querySelector('[data-geometry-support-load-master-data-open]'))return;const b=document.createElement('button');b.type='button';b.className='rvm-tool-btn';b.dataset.geometrySupportLoadMasterDataOpen='true';b.title='Manage support-load project master data';b.innerHTML='<span aria-hidden="true">LOAD</span><span>Masters</span>';section.querySelector('.rvm-ribbon-button-row')?.appendChild(b);}
function styles(){if(document.getElementById('geometry-support-load-master-data-style'))return;const s=document.createElement('style');s.id='geometry-support-load-master-data-style';s.textContent='.geometry-support-load-master-data-dialog{position:fixed;inset:0;display:none;align-items:flex-start;justify-content:center;padding:74px 20px;background:rgba(2,6,23,.56);z-index:12380}.geometry-support-load-master-data-dialog.is-open{display:flex}.gslm-card{width:min(1360px,calc(100vw - 44px));max-height:calc(100vh - 92px);overflow:auto;background:#0b1424;border:1px solid rgba(126,190,255,.30);border-radius:14px;padding:12px;color:#dbeafe}.gslm-head,.gslm-toolbar{display:flex;gap:8px;align-items:center;justify-content:space-between;flex-wrap:wrap}.gslm-toolbar{justify-content:flex-start}.gslm-head b,.gslm-card h4{color:#bfdbfe}.gslm-head small,.gslm-toolbar span,.gslm-note,.gslm-card summary{color:#9fb3cc;font-size:11px}.gslm-head button,.gslm-toolbar button{border:1px solid rgba(126,190,255,.24);border-radius:8px;background:#132238;color:#dbeafe;padding:7px 10px}.gslm-summary{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:8px;margin:8px 0}.gslm-summary div{border:1px solid rgba(126,190,255,.15);border-radius:9px;padding:8px;background:rgba(255,255,255,.035)}.gslm-summary span{display:block;color:#9fb3cc;font-size:11px}.gslm-card textarea{width:100%;min-height:220px;box-sizing:border-box;background:#08111f;color:#dbeafe;border:1px solid rgba(126,190,255,.18);border-radius:10px;padding:10px;font-family:ui-monospace,monospace;font-size:11px}.gslm-table-wrap{overflow:auto;max-height:320px}.gslm-table-wrap table{border-collapse:collapse;min-width:100%;font-size:11px}.gslm-table-wrap th,.gslm-table-wrap td{border:1px solid rgba(126,190,255,.13);padding:5px 7px;text-align:left;white-space:nowrap}.gslm-table-wrap th{position:sticky;top:0;background:#132238;color:#bfdbfe}.gslm-empty{padding:12px;border:1px dashed rgba(148,163,184,.22);border-radius:10px;color:#9fb3cc;text-align:center}';document.head.appendChild(s);}
function attach(){const root=document.querySelector('[data-rvm-viewer]');if(!root)return false;injectToolbar(root);return true;}
function click(e){if(!e.target?.closest?.('[data-geometry-support-load-master-data-open]'))return;e.preventDefault();e.stopPropagation();open();}
export function installGeometrySupportLoadMasterDataBridge(){if(typeof document==='undefined')return;if(globalThis[INSTALL_FLAG])return;globalThis[INSTALL_FLAG]=true;styles();document.addEventListener('click',click,true);let attempts=0;const wait=()=>{attempts+=1;if(!attach()&&attempts<180)setTimeout(wait,300);};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wait,{once:true});else wait();globalThis.addEventListener?.('rvm-model-loaded',()=>setTimeout(wait,320));globalThis.__PCF_GLB_GEOMETRY_SUPPORT_LOAD_MASTERS__={version:SUPPORT_LOAD_MASTER_DATA_VERSION,schema:SUPPORT_LOAD_MASTER_DATA_SCHEMA,open,current,store,summarize:summarizeSupportLoadMasterData};}
