export const RuntimeEvents = Object.freeze({
  APP_READY: 'app-ready',
  TAB_CHANGED: 'tab-changed',
  TAB_CHANGE_REQUESTED: 'tab-change-requested',
  TAB_RENDERED: 'tab-rendered',
  FILE_LOADED: 'file-loaded',
  PARSE_COMPLETE: 'parse-complete',
  RENDER_COMPLETE: 'render-complete',
  RENDER_ERROR: 'render-error',
  VIEWER3D_CONFIG_CHANGED: 'viewer3d-config-changed',
  DIAGNOSTIC_EVENT: 'diagnostic-event',
  NOTIFY: 'notify',
  SCOPE_CHANGED: 'scope-changed',
  LEGEND_CHANGED: 'legend-changed',
  GEO_TOGGLE: 'geo-toggle',
  LOAD_PINNED: 'load-pinned',
  MODEL_LOADED: 'model-loaded',
  COMPONENT_PICKED: 'component-picked',
  DEBUG_REFRESH: 'debug-refresh',
  SESSION_LOG: 'session-log',
  LOG_ADDED: 'log-added',
  TRACE_ADDED: 'trace-added',
  LOG_RESOLVED: 'log-resolved',
  SUPPORT_MAPPING_CHANGED: 'support-mapping-changed',
  SUPPORT_MAPPING_CONFIG_CHANGED: 'support-mapping-config-changed',
  SUPPORT_MAPPING_CONFIG_LOADED: 'support-mapping-config-loaded',
  SUPPORT_MAPPING_CONFIG_RESET: 'support-mapping-config-reset',
  SUPPORT_MAPPING_CONFIG_ERROR: 'support-mapping-config-error',
  DOCNO_CHANGED: 'docno-changed',
  FILE_DROPPED: 'file-dropped',
  JUMP_TO_OBJECT: 'jump-to-object',
  TRACE_CLEARED: 'trace-cleared',
  LOGS_CLEARED: 'logs-cleared',
  MODEL_EXCHANGE_IMPORTED: 'model-exchange-imported',
  MODEL_EXCHANGE_EXPORTED: 'model-exchange-exported',
  CONVERSION_CONFIG_CHANGED: 'conversion-config-changed',
  CONVERSION_CONFIG_RESET: 'conversion-config-reset',
  CONVERSION_CONFIG_LOADED: 'conversion-config-loaded',
  CONVERSION_CONFIG_ERROR: 'conversion-config-error',
  INTERCHANGE_DIAGNOSTIC: 'interchange-diagnostic',
  MODEL_CONVERTER_START: 'model-converter-start',
  MODEL_CONVERTER_SUCCESS: 'model-converter-success',
  MODEL_CONVERTER_ERROR: 'model-converter-error',
  MODEL_CONVERTER_STP_READY: 'model-converter-stp-ready',
  RVM_SOURCE_LOADED: 'rvm-source-loaded',
  RVM_MODEL_LOADED: 'rvm-model-loaded',
  RVM_NODE_SELECTED: 'rvm-node-selected',
  RVM_TAG_CREATED: 'rvm-tag-created',
  RVM_TAG_DELETED: 'rvm-tag-deleted',
  RVM_SEARCH_CHANGED: 'rvm-search-changed',
  RVM_CONFIG_CHANGED: 'rvm-config-changed',
  RVM_EXTRACT_PCF_REQUESTED: 'rvm-extract-pcf-requested',
  RVM_PCF_EXTRACT_STATE_CHANGED: 'rvm-pcf-extract-state-changed',
});

const _validEvents = new Set(Object.values(RuntimeEvents));

export function assertRuntimeEvent(name) {
  if (!_validEvents.has(name)) {
    throw new Error(`Unregistered runtime event: ${name}`);
  }
}
