/**
 * UxmlConstants.js
 *
 * Agent 00 contract constants for the Universal XML (UXML) program.
 *
 * Hard rule:
 * This file contains shared names only.
 * Do not add parsing, topology, ray, output, or master-resolution logic here.
 */

export const UXML_SCHEMA_VERSION = 'uxml-topology-v1';

export const UXML_PROFILES = Object.freeze({
  TOPOLOGY_FULL: 'UXML-TOPOLOGY-FULL',
  TOPOLOGY_LITE: 'UXML-TOPOLOGY-LITE',
  CII_BRIDGE: 'UXML-CII-BRIDGE',
  PCF_BRIDGE: 'UXML-PCF-BRIDGE',
  GLB_BRIDGE: 'UXML-GLB-BRIDGE',
  PDF_UNCERTAIN: 'UXML-PDF-UNCERTAIN',
});

export const SOURCE_FORMATS = Object.freeze({
  PDF: 'PDF',
  REV: 'REV',
  JSON: 'JSON',
  ATTRIBUTE_TXT: 'ATTRIBUTE_TXT',
  PCF: 'PCF',
  XML: 'XML',
  INPUT_XML: 'INPUT_XML',
  STANDARD_XML: 'STANDARD_XML',
  UXML: 'UXML',
});

export const XML_PROFILES = Object.freeze({
  INPUT_XML: 'INPUT_XML',
  STANDARD_XML: 'STANDARD_XML',
  BENCHMARK_XML: 'BENCHMARK_XML',
  UXML: 'UXML',
  UNKNOWN_XML: 'UNKNOWN_XML',
});

export const COMPONENT_TYPES = Object.freeze({
  PIPE: 'PIPE',
  BEND: 'BEND',
  ELBOW: 'ELBOW',
  TEE: 'TEE',
  OLET: 'OLET',
  WELDOLET: 'WELDOLET',
  SOCKOLET: 'SOCKOLET',
  VALVE: 'VALVE',
  FLANGE: 'FLANGE',
  GASKET: 'GASKET',
  REDUCER_CONCENTRIC: 'REDUCER-CONCENTRIC',
  REDUCER_ECCENTRIC: 'REDUCER-ECCENTRIC',
  CAP: 'CAP',
  BLIND_FLANGE: 'BLIND-FLANGE',
  SUPPORT: 'SUPPORT',
  UNKNOWN: 'UNKNOWN',
});

export const ANCHOR_ROLES = Object.freeze({
  EP1: 'EP1',
  EP2: 'EP2',
  CP: 'CP',
  BP: 'BP',
  POS: 'POS',
  SUPPORT_POINT: 'SUPPORT_POINT',
  OLET_HEADER_TAP: 'OLET_HEADER_TAP',
  OLET_BRANCH_POINT: 'OLET_BRANCH_POINT',
  TEE_BRANCH_POINT: 'TEE_BRANCH_POINT',
  BBOX_CENTER: 'BBOX_CENTER',
  REFERENCE_RESOLVED_POINT: 'REFERENCE_RESOLVED_POINT',
  ORI_DERIVED_POINT: 'ORI_DERIVED_POINT',
  RAY_RESOLVED_POINT: 'RAY_RESOLVED_POINT',
  MANUAL_POINT: 'MANUAL_POINT',
});

export const PORT_ROLES = Object.freeze({
  PIPE_END_1: 'PIPE_END_1',
  PIPE_END_2: 'PIPE_END_2',
  BEND_END_1: 'BEND_END_1',
  BEND_END_2: 'BEND_END_2',
  TEE_MAIN_1: 'TEE_MAIN_1',
  TEE_MAIN_2: 'TEE_MAIN_2',
  TEE_BRANCH: 'TEE_BRANCH',
  OLET_HEADER_TAP: 'OLET_HEADER_TAP',
  OLET_BRANCH: 'OLET_BRANCH',
  VALVE_END_1: 'VALVE_END_1',
  VALVE_END_2: 'VALVE_END_2',
  FLANGE_END_1: 'FLANGE_END_1',
  FLANGE_END_2: 'FLANGE_END_2',
  REDUCER_END_1: 'REDUCER_END_1',
  REDUCER_END_2: 'REDUCER_END_2',
  GASKET_END_1: 'GASKET_END_1',
  GASKET_END_2: 'GASKET_END_2',
  SUPPORT_POINT: 'SUPPORT_POINT',
});

export const SEGMENT_TYPES = Object.freeze({
  PIPE_RUN: 'PIPE_RUN',
  BEND_CHORD: 'BEND_CHORD',
  TEE_MAIN_RUN: 'TEE_MAIN_RUN',
  TEE_BRANCH_LEG: 'TEE_BRANCH_LEG',
  OLET_BRANCH_LEG: 'OLET_BRANCH_LEG',
  VALVE_AXIS: 'VALVE_AXIS',
  FLANGE_AXIS: 'FLANGE_AXIS',
  REDUCER_AXIS: 'REDUCER_AXIS',
  SUPPORT_ASSOCIATION: 'SUPPORT_ASSOCIATION',
});

export const CONFIDENCE_LEVELS = Object.freeze({
  EXACT_SOURCE: 'EXACT_SOURCE',
  ALIASED_SOURCE: 'ALIASED_SOURCE',
  REFERENCE_RESOLVED: 'REFERENCE_RESOLVED',
  ORI_DERIVED: 'ORI_DERIVED',
  RAY_RESOLVED_HOST: 'RAY_RESOLVED_HOST',
  RAY_RESOLVED_CONNECTION: 'RAY_RESOLVED_CONNECTION',
  BBOX_DERIVED: 'BBOX_DERIVED',
  TOPOLOGY_INFERRED: 'TOPOLOGY_INFERRED',
  MANUAL_RESOLVED: 'MANUAL_RESOLVED',
  UNRESOLVED: 'UNRESOLVED',
});

export const GRAPH_EDGE_CLASSES = Object.freeze({
  EXACT_CONNECTION: 'EXACT_CONNECTION',
  WITHIN_CONNECT_TOLERANCE: 'WITHIN_CONNECT_TOLERANCE',
  GAP_CANDIDATE: 'GAP_CANDIDATE',
  OVERLAP_CANDIDATE: 'OVERLAP_CANDIDATE',
  OLET_SEGMENT_TAP: 'OLET_SEGMENT_TAP',
  DISCONNECTED: 'DISCONNECTED',
  TERMINAL: 'TERMINAL',
  CONFLICT: 'CONFLICT',
  AMBIGUOUS: 'AMBIGUOUS',
});

export const RAY_DECISIONS = Object.freeze({
  AGREE: 'AGREE',
  UNIVERSAL_ONLY: 'UNIVERSAL_ONLY',
  RAY_ONLY: 'RAY_ONLY',
  PROMOTE_RAY_SAFE: 'PROMOTE_RAY_SAFE',
  PROMOTE_RAY_CANDIDATE: 'PROMOTE_RAY_CANDIDATE',
  REJECT_RAY: 'REJECT_RAY',
  MANUAL_REVIEW: 'MANUAL_REVIEW',
});

export const DIAGNOSTIC_SEVERITIES = Object.freeze({
  INFO: 'INFO',
  WARNING: 'WARNING',
  ERROR: 'ERROR',
  FATAL: 'FATAL',
});

export const UNIT_KINDS = Object.freeze({
  COORDINATE: 'COORDINATE',
  BORE: 'BORE',
  LENGTH: 'LENGTH',
  WEIGHT: 'WEIGHT',
  PRESSURE: 'PRESSURE',
  TEMPERATURE: 'TEMPERATURE',
  ROTATION: 'ROTATION',
});

export const DEFAULT_UNITS = Object.freeze({
  coordinates: 'MM',
  bore: 'MM',
  length: 'MM',
  weight: 'KG',
  pressure: 'kPa',
  temperature: 'C',
  rotation: 'DEGREES',
});

export const UXML_REQUIRED_SECTIONS = Object.freeze([
  'header',
  'sources',
  'mappings',
  'units',
  'pipelines',
  'components',
  'anchors',
  'ports',
  'segments',
  'supports',
  'topologyHints',
  'rayEvidence',
  'lossContract',
  'diagnostics',
]);

export const TOPOLOGY_HARD_RULES = Object.freeze({
  SUPPORT_EXCLUDED_FROM_PIPE_CONTINUITY: 'SUPPORT_EXCLUDED_FROM_PIPE_CONTINUITY',
  OLET_HEADER_TAP_CONNECTS_TO_SEGMENT: 'OLET_HEADER_TAP_CONNECTS_TO_SEGMENT',
  OLET_BRANCH_CONNECTS_TO_ENDPOINT: 'OLET_BRANCH_CONNECTS_TO_ENDPOINT',
  TEE_HAS_THREE_PORTS: 'TEE_HAS_THREE_PORTS',
  ONLY_PIPE_ENDPOINTS_MUTABLE: 'ONLY_PIPE_ENDPOINTS_MUTABLE',
});